In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../csvteste.csv', delimiter='\t')

In [3]:
data = data.drop(['Unnamed: 0'], axis=1)

In [4]:
from sklearn.model_selection import train_test_split
data, validation = train_test_split(data, test_size=0.1)

In [5]:
data

data         label
26187  [0.0006199219347174516, 0.05673758865248227, 0...  [-1, -1, -1]
17579  [0.001267894635711711, 0.15602836879432624, 0....  [-1, -1, -1]
5452   [0.00040393103438603184, 0.0070921985815602835...  [-1, -1, -1]
16452  [0.0011206281127584703, 0.0070921985815602835,...  [-1, -1, -1]
1628   [0.0011402636491522357, 0.05673758865248227, 0...   [1, -1, -1]
19772  [0.0010028148943958778, 0.05673758865248227, 0...  [-1, -1, -1]
49108  [0.00015848682946396388, 0.0070921985815602835...  [-1, -1, -1]
20     [0.00034502442520473555, 0.0070921985815602835...  [-1, -1, -1]
11743  [0.0013857078540743036, 0.10638297872340426, 0...  [-1, -1, -1]
645    [0.0009537260534114641, 0.0070921985815602835,...   [1, -1, -1]
15578  [0.00026648227962967376, 0.10638297872340426, ...  [-1, -1, -1]
9592   [0.001091174808167822, 0.10638297872340426, 0....  [-1, -1, -1]
45376  [0.0009242727488208159, 0.05673758865248227, 0...  [-1, -1, -1]
21399  [0.001415161158664952, 0.05673758865248227, 0....  [-1, -1, -1]
36954  [0.0005610153255361553, 0.10638297872340426, 0...  [-1, -1, -1]
19365  [0.0006690107757018652, 0.0070921985815602835,...  [-1, -1, -1]
9404   [0.0033099904206633163, 0.05673758865248227, 0...  [-1, -1, -1]
37539  [0.00046283764356732813, 0.0070921985815602835...   [-1, -1, 1]
10573  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
22290  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...   [1, -1, -1]
4672   [0.005901881224640354, 0.05673758865248227, 0....  [-1, -1, -1]
31842  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
34720  [0.002210400382612452, 0.15602836879432624, 0....   [1, -1, -1]
26406  [0.0016311520589963717, 0.10638297872340426, 0...  [-1, -1, -1]
2948   [0.0013464367812867728, 0.10638297872340426, 0...   [-1, -1, 1]
12262  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
32024  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
9454   [0.00022721120684214292, 0.0070921985815602835...  [-1, -1, -1]
33017  [0.0009929971261989949, 0.05673758865248227, 0...   [1, -1, -1]
40761  [0.0007868239940644579, 0.05673758865248227, 0...  [-1, -1, -1]
...                                                  ...           ...
22744  [0.007354910917778996, 0.20567375886524822, 0....  [-1, -1, -1]
20319  [0.00023702897503902564, 0.0070921985815602835...  [-1, -1, -1]
21622  [0.0005904686301268035, 0.0070921985815602835,...   [-1, -1, 1]
42542  [0.0016802408999807852, 0.10638297872340426, 0...  [-1, -1, -1]
23712  [0.01123292935554767, 0.0070921985815602835, 4...  [-1, -1, -1]
18654  [0.0003253888888109701, 0.0070921985815602835,...  [-1, -1, -1]
8611   [0.001798054118343378, 0.05673758865248227, 0....   [-1, -1, 1]
47872  [0.0035063457846009707, 0.15602836879432624, 0...  [-1, -1, -1]
33064  [0.0016606053635870198, 0.20567375886524822, 0...  [-1, -1, -1]
43214  [0.0007377351530800443, 0.05673758865248227, 0...  [-1, -1, -1]
6651   [0.0005511975573392726, 0.10638297872340426, 0...  [-1, -1, -1]
12183  [7.994468388890214e-05, 0.0070921985815602835,...  [-1, -1, -1]
25094  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
47063  [0.002936915229181773, 0.05673758865248227, 0....  [-1, -1, -1]
25430  [0.0048415622593770205, 0.05673758865248227, 4...   [-1, -1, 1]
30252  [0.00014866906126708115, 0.0070921985815602835...  [-1, -1, -1]
32626  [0.0010028148943958778, 0.05673758865248227, 0...   [-1, 1, -1]
16211  [0.0026816532560628224, 0.20567375886524822, 0...  [-1, -1, -1]
28227  [0.0016311520589963717, 0.15602836879432624, 0...  [-1, -1, -1]
39895  [0.004448851531501712, 0.10638297872340426, 0....  [-1, -1, -1]
36611  [8.976245208578485e-05, 0.10638297872340426, 0...  [-1, -1, -1]
38415  [1.4025383138403883e-06, 0.0070921985815602835...  [-1, -1, -1]
25061  [0.0066578493758003236, 0.05673758865248227, 0...  [-1, -1, -1]
26386  [7.012691569201941e-05, 0.0070921985815602835,...  [-1, -1, -1]
22041  [0.0015035210724368964, 0.10638297872340426, 0...   [-1, 1, -1]
26233

In [6]:
validation

data         label
29543  [0.00046283764356732813, 0.10638297872340426, ...  [-1, -1, -1]
33405  [3.0855842904488546e-05, 0.0070921985815602835...  [-1, -1, -1]
46800  [0.0005315620209455072, 0.0070921985815602835,...   [1, -1, -1]
11291  [0.001375890085877421, 0.0070921985815602835, ...   [-1, -1, 1]
49367  [0.004821926722983255, 0.05673758865248227, 8....  [-1, -1, -1]
18059  [0.0006199219347174516, 0.0070921985815602835,...   [-1, 1, -1]
19453  [0.0012875301721054764, 0.05673758865248227, 0...  [-1, -1, -1]
48506  [0.0009046372124270505, 0.10638297872340426, 0...  [-1, -1, -1]
15206  [1.4025383138403883e-06, 0.0070921985815602835...  [-1, -1, -1]
15592  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
36175  [0.0017391475091620816, 0.10638297872340426, 0...  [-1, -1, -1]
39697  [0.0009929971261989949, 0.05673758865248227, 0...  [-1, -1, -1]
49899  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
26770  [0.001650787595390137, 0.05673758865248227, 0....  [-1, -1, -1]
27217  [0.0013660723176805382, 0.05673758865248227, 0...  [-1, -1, -1]
17627  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
17283  [0.0017293297409651989, 0.10638297872340426, 0...   [-1, 1, -1]
2227   [0.001199170258333532, 0.05673758865248227, 0....  [-1, -1, -1]
47383  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
33553  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
20615  [0.0010224504307896432, 0.0, 0.0, 0.0008403191...  [-1, -1, -1]
42554  [0.002485297892125168, 0.0070921985815602835, ...   [-1, -1, 1]
2198   [0.004105229644610816, 0.05673758865248227, 0....  [-1, -1, -1]
14893  [0.004979011014133379, 0.10638297872340426, 0....  [-1, -1, -1]
40544  [0.001238441331121063, 0.15602836879432624, 0....  [-1, -1, -1]
18652  [0.001100992576364705, 0.05673758865248227, 0....  [-1, -1, -1]
48853  [0.0012777124039085937, 0.05673758865248227, 0...  [-1, -1, -1]
37792  [0.0012482590993179456, 0.05673758865248227, 0...  [-1, -1, -1]
35106  [0.0013464367812867728, 0.05673758865248227, 0...  [-1, -1, -1]
14508  [0.001758783045555847, 0.10638297872340426, 0....  [-1, -1, -1]
...                                                  ...           ...
38331  [0.00019775790225149475, 0.0070921985815602835...  [-1, -1, -1]
25939  [0.000747552921276927, 0.0070921985815602835, ...   [-1, 1, -1]
3444   [0.0005315620209455072, 0.0070921985815602835,...  [-1, -1, -1]
22918  [0.0005315620209455072, 0.0070921985815602835,...  [-1, -1, -1]
24284  [0.011547097937847917, 0.10638297872340426, 0....  [-1, -1, -1]
4680   [0.0010224504307896432, 0.05673758865248227, 0...  [-1, -1, -1]
24843  [0.00015848682946396388, 0.0070921985815602835...  [-1, -1, -1]
28354  [0.0002763000478265565, 0.05673758865248227, 0...  [-1, -1, -1]
48952  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...   [1, -1, -1]
45028  [0.0002763000478265565, 0.0070921985815602835,...  [-1, -1, -1]
14952  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
3409   [0.004183771790185879, 0.05673758865248227, 0....   [-1, 1, -1]
16372  [7.012691569201941e-05, 0.0070921985815602835,...  [-1, -1, -1]
39406  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
46434  [0.001297347940302359, 0.0070921985815602835, ...  [-1, -1, -1]
47483  [0.0004235665707797973, 0.15602836879432624, 0...  [-1, -1, -1]
23829  [0.00024684674323590837, 0.0070921985815602835...  [-1, -1, -1]
26104  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
32205  [0.0011206281127584703, 0.05673758865248227, 6...  [-1, -1, -1]
47796  [0.004203407326579644, 0.05673758865248227, 0....  [-1, -1, -1]
49556  [0.002720924328850353, 0.05673758865248227, 0....  [-1, -1, -1]
45879  [0.004350673849532884, 0.05673758865248227, 0....   [-1, 1, -1]
38915  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
42178  [0.0022693069917937483, 0.05673758865248227, 2...  [-1, -1, -1]
38762  [0.0007868239940644579, 0.0070921985815602835,...  [-1, -1, -1]
7819 

In [7]:
from ast import literal_eval

In [8]:
data

data         label
26187  [0.0006199219347174516, 0.05673758865248227, 0...  [-1, -1, -1]
17579  [0.001267894635711711, 0.15602836879432624, 0....  [-1, -1, -1]
5452   [0.00040393103438603184, 0.0070921985815602835...  [-1, -1, -1]
16452  [0.0011206281127584703, 0.0070921985815602835,...  [-1, -1, -1]
1628   [0.0011402636491522357, 0.05673758865248227, 0...   [1, -1, -1]
19772  [0.0010028148943958778, 0.05673758865248227, 0...  [-1, -1, -1]
49108  [0.00015848682946396388, 0.0070921985815602835...  [-1, -1, -1]
20     [0.00034502442520473555, 0.0070921985815602835...  [-1, -1, -1]
11743  [0.0013857078540743036, 0.10638297872340426, 0...  [-1, -1, -1]
645    [0.0009537260534114641, 0.0070921985815602835,...   [1, -1, -1]
15578  [0.00026648227962967376, 0.10638297872340426, ...  [-1, -1, -1]
9592   [0.001091174808167822, 0.10638297872340426, 0....  [-1, -1, -1]
45376  [0.0009242727488208159, 0.05673758865248227, 0...  [-1, -1, -1]
21399  [0.001415161158664952, 0.05673758865248227, 0....  [-1, -1, -1]
36954  [0.0005610153255361553, 0.10638297872340426, 0...  [-1, -1, -1]
19365  [0.0006690107757018652, 0.0070921985815602835,...  [-1, -1, -1]
9404   [0.0033099904206633163, 0.05673758865248227, 0...  [-1, -1, -1]
37539  [0.00046283764356732813, 0.0070921985815602835...   [-1, -1, 1]
10573  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
22290  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...   [1, -1, -1]
4672   [0.005901881224640354, 0.05673758865248227, 0....  [-1, -1, -1]
31842  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
34720  [0.002210400382612452, 0.15602836879432624, 0....   [1, -1, -1]
26406  [0.0016311520589963717, 0.10638297872340426, 0...  [-1, -1, -1]
2948   [0.0013464367812867728, 0.10638297872340426, 0...   [-1, -1, 1]
12262  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
32024  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
9454   [0.00022721120684214292, 0.0070921985815602835...  [-1, -1, -1]
33017  [0.0009929971261989949, 0.05673758865248227, 0...   [1, -1, -1]
40761  [0.0007868239940644579, 0.05673758865248227, 0...  [-1, -1, -1]
...                                                  ...           ...
22744  [0.007354910917778996, 0.20567375886524822, 0....  [-1, -1, -1]
20319  [0.00023702897503902564, 0.0070921985815602835...  [-1, -1, -1]
21622  [0.0005904686301268035, 0.0070921985815602835,...   [-1, -1, 1]
42542  [0.0016802408999807852, 0.10638297872340426, 0...  [-1, -1, -1]
23712  [0.01123292935554767, 0.0070921985815602835, 4...  [-1, -1, -1]
18654  [0.0003253888888109701, 0.0070921985815602835,...  [-1, -1, -1]
8611   [0.001798054118343378, 0.05673758865248227, 0....   [-1, -1, 1]
47872  [0.0035063457846009707, 0.15602836879432624, 0...  [-1, -1, -1]
33064  [0.0016606053635870198, 0.20567375886524822, 0...  [-1, -1, -1]
43214  [0.0007377351530800443, 0.05673758865248227, 0...  [-1, -1, -1]
6651   [0.0005511975573392726, 0.10638297872340426, 0...  [-1, -1, -1]
12183  [7.994468388890214e-05, 0.0070921985815602835,...  [-1, -1, -1]
25094  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
47063  [0.002936915229181773, 0.05673758865248227, 0....  [-1, -1, -1]
25430  [0.0048415622593770205, 0.05673758865248227, 4...   [-1, -1, 1]
30252  [0.00014866906126708115, 0.0070921985815602835...  [-1, -1, -1]
32626  [0.0010028148943958778, 0.05673758865248227, 0...   [-1, 1, -1]
16211  [0.0026816532560628224, 0.20567375886524822, 0...  [-1, -1, -1]
28227  [0.0016311520589963717, 0.15602836879432624, 0...  [-1, -1, -1]
39895  [0.004448851531501712, 0.10638297872340426, 0....  [-1, -1, -1]
36611  [8.976245208578485e-05, 0.10638297872340426, 0...  [-1, -1, -1]
38415  [1.4025383138403883e-06, 0.0070921985815602835...  [-1, -1, -1]
25061  [0.0066578493758003236, 0.05673758865248227, 0...  [-1, -1, -1]
26386  [7.012691569201941e-05, 0.0070921985815602835,...  [-1, -1, -1]
22041  [0.0015035210724368964, 0.10638297872340426, 0...   [-1, 1, -1]
26233

In [9]:
data = data.reset_index()
validation = validation.reset_index()
data

index                                               data         label
0      26187  [0.0006199219347174516, 0.05673758865248227, 0...  [-1, -1, -1]
1      17579  [0.001267894635711711, 0.15602836879432624, 0....  [-1, -1, -1]
2       5452  [0.00040393103438603184, 0.0070921985815602835...  [-1, -1, -1]
3      16452  [0.0011206281127584703, 0.0070921985815602835,...  [-1, -1, -1]
4       1628  [0.0011402636491522357, 0.05673758865248227, 0...   [1, -1, -1]
5      19772  [0.0010028148943958778, 0.05673758865248227, 0...  [-1, -1, -1]
6      49108  [0.00015848682946396388, 0.0070921985815602835...  [-1, -1, -1]
7         20  [0.00034502442520473555, 0.0070921985815602835...  [-1, -1, -1]
8      11743  [0.0013857078540743036, 0.10638297872340426, 0...  [-1, -1, -1]
9        645  [0.0009537260534114641, 0.0070921985815602835,...   [1, -1, -1]
10     15578  [0.00026648227962967376, 0.10638297872340426, ...  [-1, -1, -1]
11      9592  [0.001091174808167822, 0.10638297872340426, 0....  [-1, -1, -1]
12     45376  [0.0009242727488208159, 0.05673758865248227, 0...  [-1, -1, -1]
13     21399  [0.001415161158664952, 0.05673758865248227, 0....  [-1, -1, -1]
14     36954  [0.0005610153255361553, 0.10638297872340426, 0...  [-1, -1, -1]
15     19365  [0.0006690107757018652, 0.0070921985815602835,...  [-1, -1, -1]
16      9404  [0.0033099904206633163, 0.05673758865248227, 0...  [-1, -1, -1]
17     37539  [0.00046283764356732813, 0.0070921985815602835...   [-1, -1, 1]
18     10573  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
19     22290  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...   [1, -1, -1]
20      4672  [0.005901881224640354, 0.05673758865248227, 0....  [-1, -1, -1]
21     31842  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
22     34720  [0.002210400382612452, 0.15602836879432624, 0....   [1, -1, -1]
23     26406  [0.0016311520589963717, 0.10638297872340426, 0...  [-1, -1, -1]
24      2948  [0.0013464367812867728, 0.10638297872340426, 0...   [-1, -1, 1]
25     12262  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
26     32024  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
27      9454  [0.00022721120684214292, 0.0070921985815602835...  [-1, -1, -1]
28     33017  [0.0009929971261989949, 0.05673758865248227, 0...   [1, -1, -1]
29     40761  [0.0007868239940644579, 0.05673758865248227, 0...  [-1, -1, -1]
...      ...                                                ...           ...
44970  22744  [0.007354910917778996, 0.20567375886524822, 0....  [-1, -1, -1]
44971  20319  [0.00023702897503902564, 0.0070921985815602835...  [-1, -1, -1]
44972  21622  [0.0005904686301268035, 0.0070921985815602835,...   [-1, -1, 1]
44973  42542  [0.0016802408999807852, 0.10638297872340426, 0...  [-1, -1, -1]
44974  23712  [0.01123292935554767, 0.0070921985815602835, 4...  [-1, -1, -1]
44975  18654  [0.0003253888888109701, 0.0070921985815602835,...  [-1, -1, -1]
44976   8611  [0.001798054118343378, 0.05673758865248227, 0....   [-1, -1, 1]
44977  47872  [0.0035063457846009707, 0.15602836879432624, 0...  [-1, -1, -1]
44978  33064  [0.0016606053635870198, 0.20567375886524822, 0...  [-1, -1, -1]
44979  43214  [0.0007377351530800443, 0.05673758865248227, 0...  [-1, -1, -1]
44980   6651  [0.0005511975573392726, 0.10638297872340426, 0...  [-1, -1, -1]
44981  12183  [7.994468388890214e-05, 0.0070921985815602835,...  [-1, -1, -1]
44982  25094  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
44983  47063  [0.002936915229181773, 0.05673758865248227, 0....  [-1, -1, -1]
44984  25430  [0.0048415622593770205, 0.05673758865248227, 4...   [-1, -1, 1]
44985  30252  [0.00014866906126708115, 0.0070921985815602835...  [-1, -1, -1]
44986  32626  [0.0010028148943958778, 0.05673758865248227, 0...   [-1, 1, -1]
44987  16211  [0.0026816532560628224, 0.20567375886524822, 0...  [-1, -1, -1]
44988  28227  [0.0016311520589963717, 0.15602836879432624, 0...  [-1, -1, -1]
44989  39895  [0.004448851531

Como o numero de valores -1 é muito superior, na hora de gerar o batch o modelo vai tender a gerar outputs negativos, por conta disso, farei uma condição para equalizar o carregamento de batches com valores -1 iguais ao de 1. Vai deixar mais lento na hora do treino, mas deve funcionar. 

In [10]:
import random
def loadbatch(dataframe, batch_size, objective):
    if objective == 'a':
        aux = 0
    elif objective == 'u':
        aux = 1
    elif objective == 'c':
        aux = 2
    else:
        print('objetivo inexistente')
    batch_x = []
    batch_y = []
    for i in range(int(batch_size)):
        randval = random.randrange(len(dataframe))
        if random.random() > 0.5:
            while literal_eval(dataframe['label'][randval])[aux]<0:
                randval = random.randrange(len(dataframe))
        else:
            while literal_eval(dataframe['label'][randval])[aux]>0:
                randval = random.randrange(len(dataframe))
        batch_x.append(literal_eval(dataframe['data'][randval]))
        if literal_eval(dataframe['label'][randval])[aux] < 0:
            batch_y.append([0])
        else:
            batch_y.append([literal_eval(dataframe['label'][randval])[aux]])
    return batch_x, batch_y

In [11]:
xdemo, ydemo = loadbatch(data, 20, 'a')
ydemo

[[1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [0],
 [1],
 [0],
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1]]

In [12]:
singleTest = validation['label'][4449]
print(singleTest)

[-1, -1, -1]


In [13]:
import tensorflow as tf
from tensorflow.contrib import slim

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [14]:
x = tf.placeholder(tf.float32, shape=[None, 7890], name='input_placeholder')
y_ = tf.placeholder(tf.float32, shape=[None, 1])
learning_rate = tf.placeholder('float', [])

In [20]:
def model(hl):
#     hl = slim.fully_connected(tf.layers.batch_normalization(hl), 8100)
#     hl = slim.fully_connected(hl, 2000)
#     print(hl.shape)
    hl = slim.fully_connected(hl, 4000)
#     print(hl.shape)
#     hl = tf.reshape(hl, [-1, 90, 90, 1])
#     print(hl.shape)
#     hl = tf.layers.batch_normalization(slim.conv2d(hl, 16, [7, 7]))
#     print(hl.shape)
#     hl = slim.max_pool2d(hl, [3,3], stride=2)
#     residual = hl
#     print(hl.shape)
#     hl = tf.layers.batch_normalization(slim.conv2d(hl, 32, [5, 5]))
#     print(hl.shape)
#     hl = slim.max_pool2d(hl, [3,3], stride=2)
#     print(hl.shape)
#     hl = tf.layers.batch_normalization(slim.conv2d(hl, 32, [3, 3]))
#     print(hl.shape)
#     hl = slim.max_pool2d(hl, [3,3], stride=2)
#     print(hl.shape)
#     hl = slim.flatten(hl)
#     print(hl.shape)
    hl = tf.layers.batch_normalization(slim.fully_connected(hl, 1000))
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.fully_connected(hl, 50))
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.fully_connected(hl, 1))
    print(hl.shape)
    return(tf.sigmoid(hl))

In [21]:
model_1 = (model(x))

(?, 7890)
(?, 50)
(?, 1)


In [22]:
# loss = tf.reduce_mean((y_ - model_1)**2)
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y_, logits=model_1))
train = tf.train.AdamOptimizer(learning_rate).minimize(loss)

In [23]:
init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [24]:
batch_size = 20
steps = 10000
rate = 3e-4

In [25]:
with tf.Session() as sess:
    sess.run(init)
    for i in range(steps):
        batch_x, batch_y = loadbatch(data, batch_size, objective='a')
        feed = {x:batch_x, y_:batch_y, learning_rate:rate}
        sess.run(train, feed_dict=feed)
        
        if i%100 == 0:
            val_x, val_y = loadbatch(validation, 10, objective='a')
            feed_validation = {x:val_x, y_:val_y}
            print(sess.run(model_1, feed_dict=feed_validation))
            print(sess.run(loss, feed_dict=feed_validation))
            print(val_y)
            
    location = '../saved_models/kdd_model_3.ckpt'
    save_path = (saver.save(sess, location))
    print('model saved in', location)

[[0.49975002]
 [0.50671166]
 [0.49975002]
 [0.5009209 ]
 [0.49975002]
 [0.52113736]
 [0.49975002]
 [0.50953907]
 [0.49975002]
 [0.49975002]]
0.8757289
[[0], [1], [0], [0], [0], [0], [1], [0], [0], [0]]
[[0.49760056]
 [0.49760056]
 [0.49760056]
 [0.49760056]
 [0.49760056]
 [0.49760056]
 [0.49760056]
 [0.49760056]
 [0.49760056]
 [0.49760056]]
0.77354395
[[0], [0], [1], [1], [0], [0], [0], [0], [1], [1]]
[[0.4955877]
 [0.4955877]
 [0.4955877]
 [0.4955877]
 [0.4955877]
 [0.4955877]
 [0.4955877]
 [0.4955877]
 [0.4955877]
 [0.4955877]]
0.6244214
[[1], [1], [1], [0], [1], [0], [1], [1], [1], [0]]
[[0.4938797]
 [0.4938797]
 [0.4938797]
 [0.4938797]
 [0.4938797]
 [0.4938797]
 [0.4938797]
 [0.4938797]
 [0.4938797]
 [0.4938797]]
0.7233318
[[0], [1], [1], [0], [1], [1], [0], [1], [0], [0]]
[[0.49205017]
 [0.49205017]
 [0.49205017]
 [0.49205017]
 [0.49205017]
 [0.49205017]
 [0.49205017]
 [0.49205017]
 [0.49205017]
 [0.49205017]]
0.821521
[[0], [0], [1], [0], [0], [1], [0], [0], [0], [1]]
[[0.490792

[[0.4405913]
 [0.4405913]
 [0.4405913]
 [0.4405913]
 [0.4405913]
 [0.4405913]
 [0.4405913]
 [0.4405913]
 [0.4405913]
 [0.4405913]]
0.54098195
[[1], [1], [1], [1], [0], [1], [1], [1], [1], [1]]
[[0.4402785]
 [0.4402785]
 [0.4402785]
 [0.4402785]
 [0.4402785]
 [0.4402785]
 [0.4402785]
 [0.4402785]
 [0.4402785]
 [0.4402785]]
0.71718454
[[0], [0], [0], [1], [0], [1], [1], [0], [1], [1]]
[[0.43943778]
 [0.43943778]
 [0.43943778]
 [0.43943778]
 [0.43943778]
 [0.43943778]
 [0.43943778]
 [0.43943778]
 [0.43943778]
 [0.43943778]]
0.71709365
[[0], [1], [1], [0], [1], [1], [1], [0], [0], [0]]
[[0.43831822]
 [0.43831822]
 [0.43831822]
 [0.43831822]
 [0.43831822]
 [0.43831822]
 [0.43831822]
 [0.43831822]
 [0.43831822]
 [0.43831822]]
0.8923
[[0], [0], [0], [0], [0], [1], [0], [0], [0], [0]]
[[0.43744403]
 [0.43744403]
 [0.43744403]
 [0.43744403]
 [0.43744403]
 [0.43744403]
 [0.43744403]
 [0.43744403]
 [0.43744403]
 [0.43744403]]
0.71687853
[[1], [0], [1], [0], [1], [0], [0], [0], [1], [1]]
[[0.43640

[[0.38908735]
 [0.38908735]
 [0.38908735]
 [0.38908735]
 [0.38908735]
 [0.38908735]
 [0.38908735]
 [0.38908735]
 [0.38908735]
 [0.38908735]]
0.7119526
[[0], [0], [1], [0], [1], [0], [1], [1], [0], [1]]
[[0.38833448]
 [0.38833448]
 [0.38833448]
 [0.38833448]
 [0.38833448]
 [0.38833448]
 [0.38833448]
 [0.38833448]
 [0.38833448]
 [0.38833448]]
0.59538
[[1], [0], [1], [1], [1], [0], [1], [1], [1], [1]]
[[0.3870596]
 [0.3870596]
 [0.3870596]
 [0.3870596]
 [0.3870596]
 [0.3870596]
 [0.3870596]
 [0.3870596]
 [0.3870596]
 [0.3870596]]
0.6730524
[[0], [0], [1], [1], [1], [1], [0], [1], [0], [1]]
[[0.38566938]
 [0.38566938]
 [0.38566938]
 [0.38566938]
 [0.38566938]
 [0.38566938]
 [0.38566938]
 [0.38566938]
 [0.38566938]
 [0.38566938]]
0.71162564
[[1], [1], [0], [0], [1], [0], [0], [0], [1], [1]]
[[0.38439292]
 [0.38439292]
 [0.38439292]
 [0.38439292]
 [0.38439292]
 [0.38439292]
 [0.38439292]
 [0.38439292]
 [0.38439292]
 [0.38439292]]
0.7499436
[[0], [0], [1], [0], [1], [1], [0], [0], [1], [0]]
[

[[0.36242214]
 [0.36242214]
 [0.36242214]
 [0.36242214]
 [0.36242214]
 [0.36242214]
 [0.36242214]
 [0.36242214]
 [0.36242214]
 [0.36242214]]
0.7457191
[[1], [0], [1], [0], [1], [0], [0], [0], [1], [0]]
[[0.36221996]
 [0.36221996]
 [0.36221996]
 [0.36221996]
 [0.36221996]
 [0.36221996]
 [0.36221996]
 [0.36221996]
 [0.36221996]
 [0.36221996]]
0.81812465
[[0], [0], [1], [0], [1], [0], [0], [0], [0], [0]]
[[0.36191356]
 [0.36191356]
 [0.36191356]
 [0.36191356]
 [0.36191356]
 [0.36191356]
 [0.36191356]
 [0.36191356]
 [0.36191356]
 [0.36191356]]
0.6732399
[[1], [1], [0], [0], [0], [1], [0], [1], [1], [1]]
[[0.36148456]
 [0.36148456]
 [0.36148456]
 [0.36148456]
 [0.36148456]
 [0.36148456]
 [0.36148456]
 [0.36148456]
 [0.36148456]
 [0.36148456]]
0.7093929
[[0], [1], [0], [1], [1], [1], [0], [1], [0], [0]]
[[0.3609482]
 [0.3609482]
 [0.3609482]
 [0.3609482]
 [0.3609482]
 [0.3609482]
 [0.3609482]
 [0.3609482]
 [0.3609482]
 [0.3609482]]
0.63715535
[[0], [1], [1], [1], [1], [1], [1], [0], [1], [0]

[[0.4519759 ]
 [0.34945783]
 [0.34945783]
 [0.4388401 ]
 [0.49218163]
 [0.55058545]
 [0.34945783]
 [0.34945783]
 [0.4363259 ]
 [0.34945783]]
0.82777214
[[0], [0], [0], [0], [1], [0], [0], [0], [1], [0]]
[[0.3490731 ]
 [0.73417675]
 [0.3490731 ]
 [0.3490731 ]
 [0.3490731 ]
 [0.8667579 ]
 [0.3490731 ]
 [0.3490731 ]
 [0.6205989 ]
 [0.3490731 ]]
0.75215703
[[0], [1], [1], [0], [0], [0], [1], [0], [1], [0]]
[[0.38574988]
 [0.5807957 ]
 [0.34875935]
 [0.6781047 ]
 [0.34875935]
 [0.6165742 ]
 [0.34875935]
 [0.42688188]
 [0.56388295]
 [0.830982  ]]
0.63684285
[[0], [1], [0], [1], [1], [1], [0], [1], [0], [1]]
[[0.67135465]
 [0.7748509 ]
 [0.5249127 ]
 [0.34840497]
 [0.7330041 ]
 [0.34840497]
 [0.34840497]
 [0.34840497]
 [0.34840497]
 [0.51713103]]
0.7933083
[[0], [1], [1], [0], [0], [0], [0], [0], [0], [1]]
[[0.34800926]
 [0.34800926]
 [0.34800926]
 [0.588835  ]
 [0.6243222 ]
 [0.6351596 ]
 [0.6888084 ]
 [0.86797816]
 [0.3867648 ]
 [0.34800926]]
0.50561744
[[0], [1], [1], [1], [1], [1], [1], [

[[0.8642806 ]
 [0.32952842]
 [0.32952842]
 [0.32952842]
 [0.5142053 ]
 [0.32952842]
 [0.6420436 ]
 [0.9234314 ]
 [0.32952842]
 [0.9024688 ]]
0.6258125
[[1], [1], [0], [1], [1], [0], [0], [1], [0], [1]]
[[0.45306295]
 [0.43815228]
 [0.32903042]
 [0.57794845]
 [0.57204545]
 [0.32903042]
 [0.32903042]
 [0.7038717 ]
 [0.7038717 ]
 [0.75426525]]
0.6944607
[[1], [0], [0], [0], [0], [0], [1], [1], [1], [1]]
[[0.3284607 ]
 [0.3284607 ]
 [0.3284607 ]
 [0.7011292 ]
 [0.3284607 ]
 [0.44551617]
 [0.64727366]
 [0.3284607 ]
 [0.584012  ]
 [0.3284607 ]]
0.81237996
[[0], [0], [1], [0], [0], [0], [0], [1], [1], [0]]
[[0.7822756 ]
 [0.32792962]
 [0.32792962]
 [0.85884404]
 [0.32792962]
 [0.32792962]
 [0.88821065]
 [0.32792962]
 [0.32792962]
 [0.32792962]]
0.6184102
[[1], [1], [0], [1], [1], [0], [1], [1], [0], [0]]
[[0.32737803]
 [0.32737803]
 [0.32737803]
 [0.79733664]
 [0.62158215]
 [0.32737803]
 [0.56784284]
 [0.5934996 ]
 [0.52745044]
 [0.87176234]]
0.65523565
[[0], [0], [0], [1], [1], [0], [0], [1]

[[0.3067263 ]
 [0.3067263 ]
 [0.3248124 ]
 [0.95830214]
 [0.95830214]
 [0.3067263 ]
 [0.3067263 ]
 [0.3067263 ]
 [0.3067263 ]
 [0.5280932 ]]
0.58858997
[[1], [1], [1], [1], [1], [1], [0], [0], [0], [1]]
[[0.6188838 ]
 [0.3061595 ]
 [0.5404787 ]
 [0.3061595 ]
 [0.3061595 ]
 [0.40322506]
 [0.3061595 ]
 [0.3061595 ]
 [0.3061595 ]
 [0.33402288]]
0.6476634
[[1], [1], [1], [0], [1], [1], [0], [0], [0], [1]]
[[0.8747952 ]
 [0.4966364 ]
 [0.30577055]
 [0.40206754]
 [0.30577055]
 [0.30577055]
 [0.9533563 ]
 [0.75981057]
 [0.6488053 ]
 [0.30577055]]
0.7211084
[[0], [1], [1], [0], [0], [0], [1], [1], [0], [1]]
[[0.30530384]
 [0.30530384]
 [0.30530384]
 [0.30530384]
 [0.5661713 ]
 [0.30530384]
 [0.30530384]
 [0.45476028]
 [0.5646548 ]
 [0.30530384]]
0.67364377
[[0], [0], [0], [1], [1], [1], [1], [1], [0], [1]]
[[0.30486685]
 [0.67970943]
 [0.30486685]
 [0.30486685]
 [0.30486685]
 [0.9473432 ]
 [0.30486685]
 [0.40827692]
 [0.4678958 ]
 [0.7553583 ]]
0.6872503
[[0], [1], [0], [0], [0], [1], [0], [1]

[[0.28512776]
 [0.28512776]
 [0.28512776]
 [0.3258839 ]
 [0.28512776]
 [0.28512776]
 [0.28512776]
 [0.300524  ]
 [0.80391604]
 [0.2851278 ]]
0.8232988
[[0], [0], [0], [0], [1], [0], [0], [1], [0], [0]]
[[0.28459412]
 [0.28459412]
 [0.28459412]
 [0.28459412]
 [0.7016944 ]
 [0.28459412]
 [0.28459412]
 [0.9304856 ]
 [0.98921996]
 [0.8372985 ]]
0.69041574
[[0], [0], [1], [0], [1], [0], [1], [1], [0], [1]]
[[0.37067074]
 [0.28399888]
 [0.28399888]
 [0.28399888]
 [0.6008934 ]
 [0.28399888]
 [0.28399888]
 [0.28399888]
 [0.28399888]
 [0.3041923 ]]
0.75378627
[[0], [1], [0], [0], [1], [0], [0], [1], [0], [0]]
[[0.28341007]
 [0.28341007]
 [0.7318626 ]
 [0.86619365]
 [0.28341007]
 [0.28341007]
 [0.28341007]
 [0.823101  ]
 [0.28341007]
 [0.28341007]]
0.6171547
[[0], [0], [1], [1], [1], [0], [1], [1], [0], [1]]
[[0.28291976]
 [0.9068288 ]
 [0.28291976]
 [0.28291976]
 [0.28291976]
 [0.28291976]
 [0.28291976]
 [0.28291976]
 [0.28291976]
 [0.28291976]]
0.76574785
[[0], [1], [0], [1], [0], [0], [0], [0

[[0.736683  ]
 [0.26520258]
 [0.26520258]
 [0.90902805]
 [0.44708636]
 [0.26520258]
 [0.32532164]
 [0.26520258]
 [0.8963412 ]
 [0.26520255]]
0.69960254
[[0], [0], [1], [1], [0], [1], [0], [0], [1], [1]]
[[0.8998813 ]
 [0.9748121 ]
 [0.26466137]
 [0.26466137]
 [0.26466137]
 [0.3198316 ]
 [0.26466137]
 [0.99433523]
 [0.26466137]
 [0.26466137]]
0.7576793
[[1], [1], [0], [0], [0], [0], [0], [0], [0], [1]]
[[0.26416096]
 [0.26416096]
 [0.26416096]
 [0.26416096]
 [0.26416096]
 [0.26416096]
 [0.26416096]
 [0.37099224]
 [0.26416096]
 [0.26416096]]
0.76085925
[[1], [0], [1], [0], [0], [1], [0], [0], [0], [0]]
[[0.2637124 ]
 [0.2637124 ]
 [0.2637124 ]
 [0.2637124 ]
 [0.80637765]
 [0.86947924]
 [0.2637124 ]
 [0.2637124 ]
 [0.2637124 ]
 [0.2637124 ]]
0.63337207
[[1], [0], [1], [1], [1], [1], [0], [1], [0], [0]]
[[0.2632029 ]
 [0.7246211 ]
 [0.2632029 ]
 [0.2632029 ]
 [0.38917923]
 [0.2632029 ]
 [0.2632029 ]
 [0.2632029 ]
 [0.2632029 ]
 [0.2632029 ]]
0.6789912
[[0], [1], [0], [0], [1], [0], [1], [0

[[0.2454559]
 [0.2454559]
 [0.2454559]
 [0.2454559]
 [0.2454559]
 [0.3660909]
 [0.2454559]
 [0.2454559]
 [0.2454559]
 [0.2454559]]
0.6219057
[[1], [1], [1], [0], [0], [1], [1], [1], [1], [1]]
[[0.95000446]
 [0.9840329 ]
 [0.24494992]
 [0.24494992]
 [0.24494992]
 [0.8484321 ]
 [0.24494992]
 [0.4537744 ]
 [0.9840329 ]
 [0.24494992]]
0.60393333
[[1], [1], [0], [1], [1], [0], [0], [1], [1], [1]]
[[0.24448879]
 [0.24448879]
 [0.24448879]
 [0.78812355]
 [0.24448879]
 [0.24448879]
 [0.24448879]
 [0.47696096]
 [0.24448879]
 [0.24448879]]
0.7250563
[[0], [1], [1], [0], [0], [0], [1], [1], [1], [0]]
[[0.24404502]
 [0.24404502]
 [0.8706047 ]
 [0.24404502]
 [0.24404502]
 [0.24404502]
 [0.24404502]
 [0.24404502]
 [0.84531254]
 [0.24404502]]
0.67996895
[[0], [1], [1], [1], [0], [0], [0], [0], [1], [0]]
[[0.2436407 ]
 [0.2436407 ]
 [0.2436407 ]
 [0.2436407 ]
 [0.2436407 ]
 [0.2436407 ]
 [0.2436407 ]
 [0.2436407 ]
 [0.31351382]
 [0.83601874]]
0.68266046
[[0], [1], [1], [1], [0], [0], [1], [0], [0], [1

[[0.22737172]
 [0.6807186 ]
 [0.22737172]
 [0.23506777]
 [0.22737172]
 [0.22737172]
 [0.22737172]
 [0.36337394]
 [0.22737172]
 [0.22737172]]
0.69933
[[0], [1], [1], [0], [1], [0], [0], [1], [0], [0]]
[[0.22700568]
 [0.51468885]
 [0.22700568]
 [0.22700568]
 [0.9243194 ]
 [0.22700568]
 [0.7391696 ]
 [0.9272686 ]
 [0.7408207 ]
 [0.22700568]]
0.6451969
[[1], [1], [0], [1], [0], [0], [1], [1], [1], [0]]
[[0.22663705]
 [0.92301697]
 [0.65235895]
 [0.22671948]
 [0.87812734]
 [0.22663705]
 [0.41693032]
 [0.5116684 ]
 [0.22663705]
 [0.22663705]]
0.5915042
[[0], [1], [1], [0], [1], [1], [1], [1], [0], [0]]
[[0.22621515]
 [0.22621515]
 [0.22621515]
 [0.22621515]
 [0.22621515]
 [0.22621515]
 [0.22621515]
 [0.79885954]
 [0.88806933]
 [0.22621515]]
0.72003824
[[0], [1], [0], [0], [0], [1], [1], [1], [0], [1]]
[[0.9763189 ]
 [0.22581232]
 [0.36897507]
 [0.22581232]
 [0.22581232]
 [0.8395728 ]
 [0.22581232]
 [0.99178046]
 [0.22581232]
 [0.22581232]]
0.6537391
[[1], [1], [0], [0], [0], [1], [0], [1], [

[[0.21049817]
 [0.21049817]
 [0.21049817]
 [0.21049817]
 [0.22159359]
 [0.21049817]
 [0.7832112 ]
 [0.21049817]
 [0.21049817]
 [0.21049817]]
0.6554217
[[1], [1], [1], [0], [1], [1], [1], [0], [0], [0]]
[[0.21002784]
 [0.21002784]
 [0.21002784]
 [0.21002784]
 [0.21002784]
 [0.21002784]
 [0.21002784]
 [0.9849272 ]
 [0.21002784]
 [0.21002784]]
0.6710211
[[0], [1], [1], [0], [0], [0], [1], [1], [0], [1]]
[[0.20962189]
 [0.20962189]
 [0.20962189]
 [0.20962189]
 [0.20962189]
 [0.7375209 ]
 [0.6423499 ]
 [0.20962189]
 [0.20962189]
 [0.20962189]]
0.6612238
[[0], [0], [1], [1], [1], [1], [1], [0], [0], [0]]
[[0.20920098]
 [0.20920098]
 [0.20920098]
 [0.20920098]
 [0.20920098]
 [0.42847535]
 [0.20920098]
 [0.20920098]
 [0.98456556]
 [0.20920098]]
0.6198783
[[0], [1], [1], [0], [1], [1], [1], [1], [1], [0]]
[[0.20877379]
 [0.20877379]
 [0.20877379]
 [0.84294283]
 [0.20877379]
 [0.20877379]
 [0.2708857 ]
 [0.20877379]
 [0.7169586 ]
 [0.76886165]]
0.7091414
[[0], [0], [0], [1], [1], [1], [0], [0], 

[[0.19426472]
 [0.43519148]
 [0.19426472]
 [0.19426472]
 [0.19426472]
 [0.19426472]
 [0.19426472]
 [0.19426472]
 [0.19426472]
 [0.27734125]]
0.71175647
[[0], [1], [0], [0], [0], [1], [1], [0], [1], [0]]
[[0.19387494]
 [0.19387494]
 [0.19387494]
 [0.39032474]
 [0.19387494]
 [0.19387494]
 [0.19387494]
 [0.19387494]
 [0.19387494]
 [0.19387494]]
0.70882666
[[1], [0], [1], [1], [0], [0], [1], [0], [0], [0]]
[[0.19343758]
 [0.19343758]
 [0.19343758]
 [0.96559983]
 [0.19343758]
 [0.19343758]
 [0.19343758]
 [0.9453076 ]
 [0.19343758]
 [0.19343758]]
0.66203105
[[1], [0], [1], [1], [0], [0], [0], [1], [0], [0]]
[[0.19309993]
 [0.19309993]
 [0.19309993]
 [0.19309993]
 [0.882306  ]
 [0.19309993]
 [0.19309993]
 [0.50782585]
 [0.19309993]
 [0.19309993]]
0.65214634
[[0], [0], [1], [1], [1], [1], [1], [0], [1], [1]]
model saved in ./saved_models/kdd_model_3.ckpt


In [ ]:
validation.to_pickle('../validation_set.pkl')