In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../csvteste.csv', delimiter='\t')

In [3]:
data = data.drop(['Unnamed: 0'], axis=1)

In [4]:
from sklearn.model_selection import train_test_split
data, validation = train_test_split(data, test_size=0.1)

In [5]:
data

data         label
7695   [882.0, 7.0, 240.0, 244.0, 305.0, 8.0, 160.0, ...  [-1, -1, -1]
20975  [266.0, 0.0, 0.0, 28.0, 35.0, 2.0, 16.0, 230.5...  [-1, -1, -1]
20254  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
27233  [154.0, 0.0, 0.0, 160.0, 200.0, 4.0, 80.0, 253...  [-1, -1, -1]
23817  [1043.0, 7.0, 3056.0, 360.0, 450.0, 4.0, 120.0...  [-1, -1, -1]
38921  [343.0, 0.0, 0.0, 132.0, 165.0, 2.0, 0.0, 206....  [-1, -1, -1]
27390  [14.0, 0.0, 0.0, 52.0, 65.0, 0.0, 8.0, 154.32,...  [-1, -1, -1]
25987  [3122.0, 7.0, 2584.0, 408.0, 510.0, 16.0, 200....  [-1, -1, -1]
49662  [3346.0, 0.0, 4.0, 120.0, 150.0, 0.0, 48.0, 18...   [-1, 1, -1]
23975  [0.0, 0.0, 0.0, 24.0, 30.0, 0.0, 24.0, 20.08, ...  [-1, -1, -1]
34783  [245.0, -1.0, -1.0, 24.0, 30.0, 0.0, 16.0, 166...  [-1, -1, -1]
48928  [560.0, 0.0, 0.0, 340.0, 425.0, 8.0, 96.0, 179...   [-1, -1, 1]
25357  [1043.0, 0.0, 0.0, 128.0, 160.0, 2.0, 8.0, 269...  [-1, -1, -1]
30022  [882.0, 7.0, 604.0, 228.0, 285.0, 8.0, 120.0, ...  [-1, -1, -1]
11818  [133.0, 7.0, 296.0, 76.0, 95.0, 0.0, 0.0, 253....  [-1, -1, -1]
13059  [945.0, 7.0, 2884.0, 60.0, 75.0, 2.0, 16.0, 28...  [-1, -1, -1]
39304  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
49649  [889.0, 14.0, 1604.0, 132.0, 165.0, 0.0, 16.0,...  [-1, -1, -1]
12350  [1379.0, 7.0, 124.0, 64.0, 80.0, 2.0, 40.0, 28...  [-1, -1, -1]
8052   [770.0, 7.0, 540.0, 104.0, 130.0, 2.0, 32.0, 1...   [-1, 1, -1]
21620  [672.0, 7.0, 372.0, 164.0, 205.0, 2.0, 48.0, 2...  [-1, -1, -1]
32613  [1204.0, 7.0, 468.0, 664.0, 830.0, 10.0, 448.0...  [-1, -1, -1]
46064  [896.0, 7.0, 64.0, 148.0, 185.0, 8.0, 120.0, 1...  [-1, -1, -1]
30721  [1001.0, 0.0, 20.0, 60.0, 75.0, 2.0, 32.0, 166...  [-1, -1, -1]
15534  [1120.0, 14.0, 2056.0, 120.0, 150.0, 0.0, 128....  [-1, -1, -1]
10960  [14.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 701.52, ...   [1, -1, -1]
20530  [14910.0, 14.0, 1276.0, 1484.0, 1855.0, 14.0, ...   [-1, 1, -1]
30490  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
6794   [3178.0, 7.0, 2524.0, 680.0, 850.0, 6.0, 520.0...  [-1, -1, -1]
23232  [1603.0, 7.0, 504.0, 224.0, 280.0, 6.0, 240.0,...   [-1, -1, 1]
...                                                  ...           ...
29490  [3066.0, 7.0, 3324.0, 2224.0, 2780.0, 6.0, 124...  [-1, -1, -1]
1293   [511.0, 0.0, 0.0, 144.0, 180.0, 2.0, 72.0, 186...  [-1, -1, -1]
5947   [812.0, 0.0, 0.0, 184.0, 230.0, 8.0, 120.0, 16...  [-1, -1, -1]
20580  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....   [-1, -1, 1]
19735  [1834.0, 7.0, 888.0, 800.0, 1000.0, 10.0, 272....  [-1, -1, -1]
27583  [105.0, 0.0, 0.0, 176.0, 220.0, 2.0, 48.0, 123...   [-1, -1, 1]
40414  [791.0, 7.0, 1112.0, 132.0, 165.0, 2.0, 40.0, ...  [-1, -1, -1]
49703  [560.0, 0.0, 0.0, 152.0, 190.0, 0.0, 120.0, 19...  [-1, -1, -1]
45620  [777.0, 0.0, 456.0, 128.0, 160.0, 0.0, 8.0, 30...  [-1, -1, -1]
28647  [742.0, 21.0, 2148.0, 124.0, 155.0, 0.0, 8.0, ...  [-1, -1, -1]
15700  [266.0, 0.0, 0.0, 104.0, 130.0, 2.0, 24.0, 290...   [-1, -1, 1]
42056  [1106.0, 7.0, 848.0, 272.0, 340.0, 20.0, 168.0...   [1, -1, -1]
4323   [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
37160  [1225.0, 7.0, 404.0, 176.0, 220.0, 0.0, 80.0, ...  [-1, -1, -1]
20043  [966.0, 14.0, 5032.0, 180.0, 225.0, 0.0, 48.0,...  [-1, -1, -1]
43578  [770.0, 7.0, 2580.0, 156.0, 195.0, 4.0, 48.0, ...   [-1, -1, 1]
30373  [147.0, 7.0, 104.0, 0.0, 0.0, -1.0, 0.0, 166.5...   [-1, 1, -1]
23780  [742.0, 7.0, 72.0, 112.0, 140.0, 0.0, 40.0, 16...  [-1, -1, -1]
48000  [1666.0, 7.0, 1160.0, 132.0, 165.0, 0.0, 0.0, ...  [-1, -1, -1]
33129  [882.0, 14.0, 3616.0, 128.0, 160.0, 0.0, 0.0, ...   [-1, 1, -1]
23934  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
3400   [245.0, 0.0, 0.0, 32.0, 40.0, 0.0, 8.0, 166.56...  [-1, -1, -1]
33823  [812.0, 7.0, 1864.0, 172.0, 215.0, 4.0, 56.0, ...  [-1, -1, -1]
31993  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....   [1, -1, -1]
11340  [315.0, 0.0, 0.0, 24.0, 30.0, 0.0, 16.0, 196.6...   [-1, -1, 1]
28284

In [6]:
validation

data         label
12561  [2065.0, 7.0, 508.0, 240.0, 300.0, 14.0, 240.0...  [-1, -1, -1]
27981  [2569.0, 14.0, 4004.0, 152.0, 190.0, 2.0, 24.0...  [-1, -1, -1]
47997  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....   [-1, 1, -1]
39685  [126.0, 0.0, 0.0, 144.0, 180.0, 2.0, 72.0, 230...  [-1, -1, -1]
18433  [1407.0, 21.0, 3824.0, 708.0, 885.0, 8.0, 376....  [-1, -1, -1]
23335  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
38285  [784.0, 0.0, 0.0, 132.0, 165.0, 0.0, 48.0, 186...  [-1, -1, -1]
12839  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
24339  [1197.0, 21.0, 2124.0, 144.0, 180.0, 0.0, 40.0...  [-1, -1, -1]
21560  [819.0, 14.0, 560.0, 128.0, 160.0, 0.0, 0.0, 2...  [-1, -1, -1]
39664  [210.0, 0.0, 0.0, 200.0, 250.0, 0.0, 64.0, 400...   [-1, -1, 1]
44153  [371.0, 0.0, 0.0, 132.0, 165.0, 0.0, 0.0, 266....   [-1, -1, 1]
44292  [56.0, 0.0, 0.0, 108.0, 135.0, 0.0, 24.0, 186....  [-1, -1, -1]
36163  [0.0, 0.0, 0.0, 20.0, 25.0, 0.0, 32.0, 166.56,...  [-1, -1, -1]
14690  [623.0, 7.0, 232.0, 148.0, 185.0, 2.0, 16.0, 2...   [-1, -1, 1]
6832   [203.0, 0.0, 0.0, 196.0, 245.0, 10.0, 24.0, 18...  [-1, -1, -1]
21614  [1589.0, 14.0, 3340.0, 344.0, 430.0, 0.0, 128....  [-1, -1, -1]
18039  [574.0, 7.0, 968.0, 100.0, 125.0, 6.0, 88.0, 2...   [-1, -1, 1]
18347  [847.0, 7.0, 4416.0, 208.0, 260.0, 4.0, 104.0,...   [-1, -1, 1]
17157  [0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 293.36, 0...  [-1, -1, -1]
34128  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
8368   [1099.0, 7.0, 0.0, 88.0, 110.0, 2.0, 40.0, 212...  [-1, -1, -1]
27819  [791.0, 7.0, 5500.0, 128.0, 160.0, 6.0, 8.0, 2...  [-1, -1, -1]
4860   [210.0, 7.0, 252.0, 60.0, 75.0, 0.0, 56.0, 166...  [-1, -1, -1]
10923  [1274.0, 7.0, 172.0, 164.0, 205.0, 2.0, 64.0, ...  [-1, -1, -1]
34137  [679.0, 7.0, 2392.0, 116.0, 145.0, 2.0, 8.0, 1...  [-1, -1, -1]
32357  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
32521  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
8702   [840.0, 7.0, 3076.0, 120.0, 150.0, 0.0, 0.0, 2...  [-1, -1, -1]
7622   [973.0, 7.0, 1172.0, 168.0, 210.0, 0.0, 72.0, ...  [-1, -1, -1]
...                                                  ...           ...
9016   [0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 253.52, 0...  [-1, -1, -1]
27524  [6993.0, 21.0, 4364.0, 168.0, 210.0, 4.0, 48.0...  [-1, -1, -1]
45101  [1638.0, 7.0, 4464.0, 464.0, 580.0, 8.0, 240.0...   [-1, 1, -1]
43366  [756.0, 7.0, 20.0, 140.0, 175.0, 0.0, 24.0, 30...  [-1, -1, -1]
11508  [742.0, 14.0, 232.0, 96.0, 120.0, 0.0, 32.0, 2...  [-1, -1, -1]
16115  [455.0, 7.0, 1912.0, 12.0, 15.0, 0.0, 0.0, 186...  [-1, -1, -1]
41447  [1449.0, 7.0, 228.0, 172.0, 215.0, 2.0, 168.0,...   [-1, -1, 1]
1620   [1029.0, 14.0, 2936.0, 168.0, 210.0, 6.0, 64.0...  [-1, -1, -1]
3948   [1393.0, 7.0, 1520.0, 160.0, 200.0, 0.0, 16.0,...  [-1, -1, -1]
40467  [2611.0, 14.0, 2188.0, 292.0, 365.0, 0.0, 176....  [-1, -1, -1]
22056  [602.0, 14.0, 684.0, 148.0, 185.0, 0.0, 32.0, ...  [-1, -1, -1]
5897   [224.0, 0.0, 0.0, 36.0, 45.0, 0.0, 16.0, 200.0...  [-1, -1, -1]
2717   [70.0, -1.0, -1.0, 124.0, 155.0, 6.0, 32.0, 25...   [-1, -1, 1]
12535  [700.0, 7.0, 4.0, 132.0, 165.0, 0.0, 32.0, 186...  [-1, -1, -1]
31023  [1953.0, 7.0, 0.0, 240.0, 300.0, 0.0, 72.0, 25...  [-1, -1, -1]
9539   [1540.0, 7.0, 388.0, 284.0, 355.0, 0.0, 0.0, 2...  [-1, -1, -1]
42126  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
8082   [322.0, 0.0, 0.0, 116.0, 145.0, 0.0, 8.0, 266....  [-1, -1, -1]
18911  [0.0, 0.0, 0.0, 80.0, 100.0, 0.0, 80.0, 166.56...  [-1, -1, -1]
36935  [812.0, 0.0, 0.0, 192.0, 240.0, 2.0, 48.0, 503...  [-1, -1, -1]
37889  [1001.0, 0.0, 0.0, 304.0, 380.0, 20.0, 256.0, ...  [-1, -1, -1]
46840  [917.0, 7.0, 208.0, 128.0, 160.0, 0.0, 8.0, 28...   [-1, -1, 1]
22743  [1029.0, 14.0, 1272.0, 88.0, 110.0, 8.0, 32.0,...  [-1, -1, -1]
28413  [1267.0, 7.0, 1156.0, 348.0, 435.0, 10.0, 160....  [-1, -1, -1]
47458  [1449.0, 14.0, 6048.0, 240.0, 300.0, 10.0, 128...  [-1, -1, -1]
16509

In [7]:
from ast import literal_eval

In [8]:
data

data         label
7695   [882.0, 7.0, 240.0, 244.0, 305.0, 8.0, 160.0, ...  [-1, -1, -1]
20975  [266.0, 0.0, 0.0, 28.0, 35.0, 2.0, 16.0, 230.5...  [-1, -1, -1]
20254  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
27233  [154.0, 0.0, 0.0, 160.0, 200.0, 4.0, 80.0, 253...  [-1, -1, -1]
23817  [1043.0, 7.0, 3056.0, 360.0, 450.0, 4.0, 120.0...  [-1, -1, -1]
38921  [343.0, 0.0, 0.0, 132.0, 165.0, 2.0, 0.0, 206....  [-1, -1, -1]
27390  [14.0, 0.0, 0.0, 52.0, 65.0, 0.0, 8.0, 154.32,...  [-1, -1, -1]
25987  [3122.0, 7.0, 2584.0, 408.0, 510.0, 16.0, 200....  [-1, -1, -1]
49662  [3346.0, 0.0, 4.0, 120.0, 150.0, 0.0, 48.0, 18...   [-1, 1, -1]
23975  [0.0, 0.0, 0.0, 24.0, 30.0, 0.0, 24.0, 20.08, ...  [-1, -1, -1]
34783  [245.0, -1.0, -1.0, 24.0, 30.0, 0.0, 16.0, 166...  [-1, -1, -1]
48928  [560.0, 0.0, 0.0, 340.0, 425.0, 8.0, 96.0, 179...   [-1, -1, 1]
25357  [1043.0, 0.0, 0.0, 128.0, 160.0, 2.0, 8.0, 269...  [-1, -1, -1]
30022  [882.0, 7.0, 604.0, 228.0, 285.0, 8.0, 120.0, ...  [-1, -1, -1]
11818  [133.0, 7.0, 296.0, 76.0, 95.0, 0.0, 0.0, 253....  [-1, -1, -1]
13059  [945.0, 7.0, 2884.0, 60.0, 75.0, 2.0, 16.0, 28...  [-1, -1, -1]
39304  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
49649  [889.0, 14.0, 1604.0, 132.0, 165.0, 0.0, 16.0,...  [-1, -1, -1]
12350  [1379.0, 7.0, 124.0, 64.0, 80.0, 2.0, 40.0, 28...  [-1, -1, -1]
8052   [770.0, 7.0, 540.0, 104.0, 130.0, 2.0, 32.0, 1...   [-1, 1, -1]
21620  [672.0, 7.0, 372.0, 164.0, 205.0, 2.0, 48.0, 2...  [-1, -1, -1]
32613  [1204.0, 7.0, 468.0, 664.0, 830.0, 10.0, 448.0...  [-1, -1, -1]
46064  [896.0, 7.0, 64.0, 148.0, 185.0, 8.0, 120.0, 1...  [-1, -1, -1]
30721  [1001.0, 0.0, 20.0, 60.0, 75.0, 2.0, 32.0, 166...  [-1, -1, -1]
15534  [1120.0, 14.0, 2056.0, 120.0, 150.0, 0.0, 128....  [-1, -1, -1]
10960  [14.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 701.52, ...   [1, -1, -1]
20530  [14910.0, 14.0, 1276.0, 1484.0, 1855.0, 14.0, ...   [-1, 1, -1]
30490  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
6794   [3178.0, 7.0, 2524.0, 680.0, 850.0, 6.0, 520.0...  [-1, -1, -1]
23232  [1603.0, 7.0, 504.0, 224.0, 280.0, 6.0, 240.0,...   [-1, -1, 1]
...                                                  ...           ...
29490  [3066.0, 7.0, 3324.0, 2224.0, 2780.0, 6.0, 124...  [-1, -1, -1]
1293   [511.0, 0.0, 0.0, 144.0, 180.0, 2.0, 72.0, 186...  [-1, -1, -1]
5947   [812.0, 0.0, 0.0, 184.0, 230.0, 8.0, 120.0, 16...  [-1, -1, -1]
20580  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....   [-1, -1, 1]
19735  [1834.0, 7.0, 888.0, 800.0, 1000.0, 10.0, 272....  [-1, -1, -1]
27583  [105.0, 0.0, 0.0, 176.0, 220.0, 2.0, 48.0, 123...   [-1, -1, 1]
40414  [791.0, 7.0, 1112.0, 132.0, 165.0, 2.0, 40.0, ...  [-1, -1, -1]
49703  [560.0, 0.0, 0.0, 152.0, 190.0, 0.0, 120.0, 19...  [-1, -1, -1]
45620  [777.0, 0.0, 456.0, 128.0, 160.0, 0.0, 8.0, 30...  [-1, -1, -1]
28647  [742.0, 21.0, 2148.0, 124.0, 155.0, 0.0, 8.0, ...  [-1, -1, -1]
15700  [266.0, 0.0, 0.0, 104.0, 130.0, 2.0, 24.0, 290...   [-1, -1, 1]
42056  [1106.0, 7.0, 848.0, 272.0, 340.0, 20.0, 168.0...   [1, -1, -1]
4323   [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
37160  [1225.0, 7.0, 404.0, 176.0, 220.0, 0.0, 80.0, ...  [-1, -1, -1]
20043  [966.0, 14.0, 5032.0, 180.0, 225.0, 0.0, 48.0,...  [-1, -1, -1]
43578  [770.0, 7.0, 2580.0, 156.0, 195.0, 4.0, 48.0, ...   [-1, -1, 1]
30373  [147.0, 7.0, 104.0, 0.0, 0.0, -1.0, 0.0, 166.5...   [-1, 1, -1]
23780  [742.0, 7.0, 72.0, 112.0, 140.0, 0.0, 40.0, 16...  [-1, -1, -1]
48000  [1666.0, 7.0, 1160.0, 132.0, 165.0, 0.0, 0.0, ...  [-1, -1, -1]
33129  [882.0, 14.0, 3616.0, 128.0, 160.0, 0.0, 0.0, ...   [-1, 1, -1]
23934  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
3400   [245.0, 0.0, 0.0, 32.0, 40.0, 0.0, 8.0, 166.56...  [-1, -1, -1]
33823  [812.0, 7.0, 1864.0, 172.0, 215.0, 4.0, 56.0, ...  [-1, -1, -1]
31993  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....   [1, -1, -1]
11340  [315.0, 0.0, 0.0, 24.0, 30.0, 0.0, 16.0, 196.6...   [-1, -1, 1]
28284

In [9]:
data = data.reset_index()
validation = validation.reset_index()
data

index                                               data         label
0       7695  [882.0, 7.0, 240.0, 244.0, 305.0, 8.0, 160.0, ...  [-1, -1, -1]
1      20975  [266.0, 0.0, 0.0, 28.0, 35.0, 2.0, 16.0, 230.5...  [-1, -1, -1]
2      20254  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
3      27233  [154.0, 0.0, 0.0, 160.0, 200.0, 4.0, 80.0, 253...  [-1, -1, -1]
4      23817  [1043.0, 7.0, 3056.0, 360.0, 450.0, 4.0, 120.0...  [-1, -1, -1]
5      38921  [343.0, 0.0, 0.0, 132.0, 165.0, 2.0, 0.0, 206....  [-1, -1, -1]
6      27390  [14.0, 0.0, 0.0, 52.0, 65.0, 0.0, 8.0, 154.32,...  [-1, -1, -1]
7      25987  [3122.0, 7.0, 2584.0, 408.0, 510.0, 16.0, 200....  [-1, -1, -1]
8      49662  [3346.0, 0.0, 4.0, 120.0, 150.0, 0.0, 48.0, 18...   [-1, 1, -1]
9      23975  [0.0, 0.0, 0.0, 24.0, 30.0, 0.0, 24.0, 20.08, ...  [-1, -1, -1]
10     34783  [245.0, -1.0, -1.0, 24.0, 30.0, 0.0, 16.0, 166...  [-1, -1, -1]
11     48928  [560.0, 0.0, 0.0, 340.0, 425.0, 8.0, 96.0, 179...   [-1, -1, 1]
12     25357  [1043.0, 0.0, 0.0, 128.0, 160.0, 2.0, 8.0, 269...  [-1, -1, -1]
13     30022  [882.0, 7.0, 604.0, 228.0, 285.0, 8.0, 120.0, ...  [-1, -1, -1]
14     11818  [133.0, 7.0, 296.0, 76.0, 95.0, 0.0, 0.0, 253....  [-1, -1, -1]
15     13059  [945.0, 7.0, 2884.0, 60.0, 75.0, 2.0, 16.0, 28...  [-1, -1, -1]
16     39304  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
17     49649  [889.0, 14.0, 1604.0, 132.0, 165.0, 0.0, 16.0,...  [-1, -1, -1]
18     12350  [1379.0, 7.0, 124.0, 64.0, 80.0, 2.0, 40.0, 28...  [-1, -1, -1]
19      8052  [770.0, 7.0, 540.0, 104.0, 130.0, 2.0, 32.0, 1...   [-1, 1, -1]
20     21620  [672.0, 7.0, 372.0, 164.0, 205.0, 2.0, 48.0, 2...  [-1, -1, -1]
21     32613  [1204.0, 7.0, 468.0, 664.0, 830.0, 10.0, 448.0...  [-1, -1, -1]
22     46064  [896.0, 7.0, 64.0, 148.0, 185.0, 8.0, 120.0, 1...  [-1, -1, -1]
23     30721  [1001.0, 0.0, 20.0, 60.0, 75.0, 2.0, 32.0, 166...  [-1, -1, -1]
24     15534  [1120.0, 14.0, 2056.0, 120.0, 150.0, 0.0, 128....  [-1, -1, -1]
25     10960  [14.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 701.52, ...   [1, -1, -1]
26     20530  [14910.0, 14.0, 1276.0, 1484.0, 1855.0, 14.0, ...   [-1, 1, -1]
27     30490  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
28      6794  [3178.0, 7.0, 2524.0, 680.0, 850.0, 6.0, 520.0...  [-1, -1, -1]
29     23232  [1603.0, 7.0, 504.0, 224.0, 280.0, 6.0, 240.0,...   [-1, -1, 1]
...      ...                                                ...           ...
44970  29490  [3066.0, 7.0, 3324.0, 2224.0, 2780.0, 6.0, 124...  [-1, -1, -1]
44971   1293  [511.0, 0.0, 0.0, 144.0, 180.0, 2.0, 72.0, 186...  [-1, -1, -1]
44972   5947  [812.0, 0.0, 0.0, 184.0, 230.0, 8.0, 120.0, 16...  [-1, -1, -1]
44973  20580  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....   [-1, -1, 1]
44974  19735  [1834.0, 7.0, 888.0, 800.0, 1000.0, 10.0, 272....  [-1, -1, -1]
44975  27583  [105.0, 0.0, 0.0, 176.0, 220.0, 2.0, 48.0, 123...   [-1, -1, 1]
44976  40414  [791.0, 7.0, 1112.0, 132.0, 165.0, 2.0, 40.0, ...  [-1, -1, -1]
44977  49703  [560.0, 0.0, 0.0, 152.0, 190.0, 0.0, 120.0, 19...  [-1, -1, -1]
44978  45620  [777.0, 0.0, 456.0, 128.0, 160.0, 0.0, 8.0, 30...  [-1, -1, -1]
44979  28647  [742.0, 21.0, 2148.0, 124.0, 155.0, 0.0, 8.0, ...  [-1, -1, -1]
44980  15700  [266.0, 0.0, 0.0, 104.0, 130.0, 2.0, 24.0, 290...   [-1, -1, 1]
44981  42056  [1106.0, 7.0, 848.0, 272.0, 340.0, 20.0, 168.0...   [1, -1, -1]
44982   4323  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1....  [-1, -1, -1]
44983  37160  [1225.0, 7.0, 404.0, 176.0, 220.0, 0.0, 80.0, ...  [-1, -1, -1]
44984  20043  [966.0, 14.0, 5032.0, 180.0, 225.0, 0.0, 48.0,...  [-1, -1, -1]
44985  43578  [770.0, 7.0, 2580.0, 156.0, 195.0, 4.0, 48.0, ...   [-1, -1, 1]
44986  30373  [147.0, 7.0, 104.0, 0.0, 0.0, -1.0, 0.0, 166.5...   [-1, 1, -1]
44987  23780  [742.0, 7.0, 72.0, 112.0, 140.0, 0.0, 40.0, 16...  [-1, -1, -1]
44988  48000  [1666.0, 7.0, 1160.0, 132.0, 165.0, 0.0, 0.0, ...  [-1, -1, -1]
44989  33129  [882.0, 14.0, 3

Como o numero de valores -1 é muito superior, na hora de gerar o batch o modelo vai tender a gerar outputs negativos, por conta disso, farei uma condição para equalizar o carregamento de batches com valores -1 iguais ao de 1. Vai deixar mais lento na hora do treino, mas deve funcionar. 

In [10]:
import random
def loadbatch(dataframe, batch_size, objective):
    if objective == 'a':
        aux = 0
    elif objective == 'u':
        aux = 1
    elif objective == 'c':
        aux = 2
    else:
        print('objetivo inexistente')
    batch_x = []
    batch_y = []
    for i in range(int(batch_size)):
        randval = random.randrange(len(dataframe))
        if random.random() > 0.5:
            while literal_eval(dataframe['label'][randval])[aux]<0:
                randval = random.randrange(len(dataframe))
        else:
            while literal_eval(dataframe['label'][randval])[aux]>0:
                randval = random.randrange(len(dataframe))
        batch_x.append(literal_eval(dataframe['data'][randval]))
        if literal_eval(dataframe['label'][randval])[aux] < 0:
            batch_y.append([0])
        else:
            batch_y.append([literal_eval(dataframe['label'][randval])[aux]])
    return batch_x, batch_y

In [11]:
xdemo, ydemo = loadbatch(data, 20, 'a')
ydemo

[[1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0]]

In [12]:
singleTest = validation['label'][4449]
print(singleTest)

[-1, -1, -1]


In [13]:
import tensorflow as tf
from tensorflow.contrib import slim

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [14]:
x = tf.placeholder(tf.float32, shape=[None, 7890], name='input_placeholder')
y_ = tf.placeholder(tf.float32, shape=[None, 1])
learning_rate = tf.placeholder('float', [])

In [49]:
def model(hl):
    hl = slim.fully_connected(tf.layers.batch_normalization(hl), 8100)
#     hl = slim.fully_connected(hl, 2000)
#     print(hl.shape)
#     hl = slim.fully_connected(hl, 2000)
#     print(hl.shape)
    hl = tf.reshape(hl, [-1, 90, 90, 1])
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.conv2d(hl, 16, [7, 7]))
    print(hl.shape)
    hl = slim.max_pool2d(hl, [3,3], stride=2)
    residual = hl
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.conv2d(hl, 32, [5, 5]))
    print(hl.shape)
    hl = slim.max_pool2d(hl, [3,3], stride=2)
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.conv2d(hl, 32, [3, 3]))
    print(hl.shape)
    hl = slim.max_pool2d(hl, [3,3], stride=2)
    print(hl.shape)
    hl = slim.flatten(hl)
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.fully_connected(hl, 1000))
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.fully_connected(hl, 100))
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.fully_connected(hl, 1))
    print(hl.shape)
    return(tf.sigmoid(hl))

In [50]:
model_1 = (model(x))

(?, 90, 90, 1)
(?, 90, 90, 16)
(?, 44, 44, 16)
(?, 44, 44, 32)
(?, 21, 21, 32)
(?, 21, 21, 32)
(?, 10, 10, 32)
(?, 3200)
(?, 1000)
(?, 100)
(?, 1)


In [51]:
# loss = tf.reduce_mean((y_ - model_1)**2)
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y_, logits=model_1))
train = tf.train.AdamOptimizer(learning_rate).minimize(loss)

In [52]:
init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [53]:
batch_size = 4
steps = 5000
rate = 0.0001

In [ ]:
with tf.Session() as sess:
    sess.run(init)
    for i in range(steps):
        batch_x, batch_y = loadbatch(data, batch_size, objective='a')
        feed = {x:batch_x, y_:batch_y, learning_rate:rate}
        sess.run(train, feed_dict=feed)
        
        if i%10 == 0:
            val_x, val_y = loadbatch(validation, 10, objective='a')
            feed_validation = {x:val_x, y_:val_y}
            print(sess.run(model_1, feed_dict=feed_validation))
            print(sess.run(loss, feed_dict=feed_validation))
            print(val_y)
            if i>1000:
                rate = 3e-4
            
    location = './saved_models/kdd_model_3.ckpt'
    save_path = (saver.save(sess, location))
    print('model saved in', location)

[[0.50002503]
 [0.50002503]
 [0.50002503]
 [0.50002503]
 [0.50002503]
 [0.50002503]
 [0.50002503]
 [0.50002503]
 [0.50002503]
 [0.50002503]]
0.72408
[[0], [0], [0], [1], [0], [1], [1], [1], [1], [0]]
[[0.49997354]
 [0.49997354]
 [0.49997354]
 [0.49997354]
 [0.49997354]
 [0.49997354]
 [0.49997354]
 [0.49997354]
 [0.49997354]
 [0.49997354]]
0.7740711
[[0], [0], [0], [1], [0], [0], [1], [1], [0], [1]]
[[0.4999136]
 [0.4999136]
 [0.4999136]
 [0.4999136]
 [0.4999136]
 [0.4999136]
 [0.4999136]
 [0.4999136]
 [0.4999136]
 [0.4999136]]
0.674075
[[1], [0], [0], [0], [1], [0], [1], [1], [1], [1]]
[[0.49981183]
 [0.49981183]
 [0.49981183]
 [0.49981183]
 [0.49981183]
 [0.49981183]
 [0.49981183]
 [0.49981183]
 [0.49981183]
 [0.49981183]]
0.6740728
[[0], [1], [0], [1], [1], [1], [1], [1], [0], [0]]
[[0.49973014]
 [0.49973014]
 [0.49973014]
 [0.49973014]
 [0.49973014]
 [0.49973014]
 [0.49973014]
 [0.49973014]
 [0.49973014]
 [0.49973014]]
0.62409794
[[1], [0], [1], [0], [0], [1], [1], [1], [1], [1]]
[[

[[0.4955607]
 [0.4955607]
 [0.4955607]
 [0.4955607]
 [0.4955607]
 [0.4955607]
 [0.4955607]
 [0.4955607]
 [0.4955607]
 [0.4955607]]
0.7730917
[[1], [0], [0], [0], [0], [0], [0], [1], [1], [1]]
[[0.49548936]
 [0.49548936]
 [0.49548936]
 [0.49548936]
 [0.49548936]
 [0.49548936]
 [0.49548936]
 [0.49548936]
 [0.49548936]
 [0.49548936]]
0.6739781
[[1], [0], [1], [0], [0], [0], [1], [1], [1], [1]]
[[0.4954255]
 [0.4954255]
 [0.4954255]
 [0.4954255]
 [0.4954255]
 [0.4954255]
 [0.4954255]
 [0.4954255]
 [0.4954255]
 [0.4954255]]
0.6244341
[[1], [1], [1], [1], [0], [1], [0], [0], [1], [1]]
[[0.49534598]
 [0.49534598]
 [0.49534598]
 [0.49534598]
 [0.49534598]
 [0.49534598]
 [0.49534598]
 [0.49534598]
 [0.49534598]
 [0.49534598]]
0.8225788
[[0], [0], [0], [0], [1], [0], [0], [1], [0], [1]]
[[0.4952175]
 [0.4952175]
 [0.4952175]
 [0.4952175]
 [0.4952175]
 [0.4952175]
 [0.4952175]
 [0.4952175]
 [0.4952175]
 [0.4952175]]
0.72349405
[[0], [0], [1], [1], [1], [1], [0], [0], [0], [1]]
[[0.49503222]
 [0.4

[[0.4915081]
 [0.4915081]
 [0.4915081]
 [0.4915081]
 [0.4915081]
 [0.4915081]
 [0.4915081]
 [0.4915081]
 [0.4915081]
 [0.4915081]]
0.7230455
[[1], [1], [0], [1], [0], [0], [0], [1], [0], [1]]
[[0.49142995]
 [0.49142995]
 [0.49142995]
 [0.49142995]
 [0.49142995]
 [0.49142995]
 [0.49142995]
 [0.49142995]
 [0.49142995]
 [0.49142995]]
0.7230361
[[0], [1], [0], [1], [0], [0], [1], [1], [0], [1]]
[[0.4913492]
 [0.4913492]
 [0.4913492]
 [0.4913492]
 [0.4913492]
 [0.4913492]
 [0.4913492]
 [0.4913492]
 [0.4913492]
 [0.4913492]]
0.7230264
[[1], [0], [1], [0], [0], [0], [1], [1], [0], [1]]
[[0.49132293]
 [0.49132293]
 [0.49132293]
 [0.49132293]
 [0.49132293]
 [0.49132293]
 [0.49132293]
 [0.49132293]
 [0.49132293]
 [0.49132293]]
0.5756264
[[0], [1], [1], [1], [1], [1], [1], [0], [1], [1]]
[[0.49124053]
 [0.49124053]
 [0.49124053]
 [0.49124053]
 [0.49124053]
 [0.49124053]
 [0.49124053]
 [0.49124053]
 [0.49124053]
 [0.49124053]]
0.77213746
[[0], [1], [0], [0], [0], [1], [1], [0], [0], [1]]
[[0.49111

[[0.4815396]
 [0.4815396]
 [0.4815396]
 [0.4815396]
 [0.4815396]
 [0.4815396]
 [0.4815396]
 [0.4815396]
 [0.4815396]
 [0.4815396]]
0.77001035
[[0], [0], [0], [0], [1], [1], [1], [1], [0], [0]]
[[0.48124862]
 [0.48124862]
 [0.48124862]
 [0.48124862]
 [0.48124862]
 [0.48124862]
 [0.48124862]
 [0.48124862]
 [0.48124862]
 [0.48124862]]
0.6255723
[[1], [1], [1], [1], [0], [1], [1], [0], [1], [0]]
[[0.48088512]
 [0.48088512]
 [0.48088512]
 [0.48088512]
 [0.48088512]
 [0.48088512]
 [0.48088512]
 [0.48088512]
 [0.48088512]
 [0.48088512]]
0.7698677
[[1], [0], [0], [0], [1], [1], [0], [0], [1], [0]]
[[0.4805269]
 [0.4805269]
 [0.4805269]
 [0.4805269]
 [0.4805269]
 [0.4805269]
 [0.4805269]
 [0.4805269]
 [0.4805269]
 [0.4805269]]
0.7697896
[[0], [0], [0], [0], [1], [0], [1], [1], [0], [1]]
[[0.48015535]
 [0.48015535]
 [0.48015535]
 [0.48015535]
 [0.48015535]
 [0.48015535]
 [0.48015535]
 [0.48015535]
 [0.48015535]
 [0.48015535]]
0.6256621
[[0], [0], [1], [1], [1], [0], [1], [1], [1], [1]]
[[0.47986

[[0.4697575]
 [0.4697575]
 [0.4697575]
 [0.4697575]
 [0.4697575]
 [0.4697575]
 [0.4697575]
 [0.4697575]
 [0.4697575]
 [0.4697575]]
0.7204813
[[0], [1], [0], [1], [1], [0], [0], [1], [0], [1]]
[[0.46957806]
 [0.46957806]
 [0.46957806]
 [0.46957806]
 [0.46957806]
 [0.46957806]
 [0.46957806]
 [0.46957806]
 [0.46957806]
 [0.46957806]]
0.72046053
[[1], [0], [1], [0], [0], [1], [1], [0], [1], [0]]
[[0.46925893]
 [0.46925893]
 [0.46925893]
 [0.46925893]
 [0.46925893]
 [0.46925893]
 [0.46925893]
 [0.46925893]
 [0.46925893]
 [0.46925893]]
0.62657195
[[1], [1], [1], [1], [1], [0], [0], [1], [0], [1]]
[[0.468916]
 [0.468916]
 [0.468916]
 [0.468916]
 [0.468916]
 [0.468916]
 [0.468916]
 [0.468916]
 [0.468916]
 [0.468916]]
0.62660104
[[1], [1], [0], [1], [0], [1], [1], [1], [0], [1]]
[[0.46856454]
 [0.46856454]
 [0.46856454]
 [0.46856454]
 [0.46856454]
 [0.46856454]
 [0.46856454]
 [0.46856454]
 [0.46856454]
 [0.46856454]]
0.7672003
[[0], [0], [0], [0], [1], [0], [1], [0], [1], [1]]
[[0.46829805]
 [0

[[0.45771196]
 [0.45771196]
 [0.45771196]
 [0.45771196]
 [0.45771196]
 [0.45771196]
 [0.45771196]
 [0.45771196]
 [0.45771196]
 [0.45771196]]
0.7191093
[[1], [0], [0], [1], [0], [0], [1], [1], [1], [0]]
[[0.45726368]
 [0.45726368]
 [0.45726368]
 [0.45726368]
 [0.45726368]
 [0.45726368]
 [0.45726368]
 [0.45726368]
 [0.45726368]
 [0.45726368]]
0.856238
[[0], [0], [0], [0], [0], [1], [0], [1], [0], [0]]
[[0.45691666]
 [0.45691666]
 [0.45691666]
 [0.45691666]
 [0.45691666]
 [0.45691666]
 [0.45691666]
 [0.45691666]
 [0.45691666]
 [0.45691666]]
0.6733282
[[1], [1], [0], [1], [1], [0], [0], [1], [1], [0]]
[[0.45665818]
 [0.45665818]
 [0.45665818]
 [0.45665818]
 [0.45665818]
 [0.45665818]
 [0.45665818]
 [0.45665818]
 [0.45665818]
 [0.45665818]]
0.6276592
[[0], [1], [1], [0], [1], [1], [1], [1], [0], [1]]
[[0.4564362]
 [0.4564362]
 [0.4564362]
 [0.4564362]
 [0.4564362]
 [0.4564362]
 [0.4564362]
 [0.4564362]
 [0.4564362]
 [0.4564362]]
0.76460963
[[0], [0], [1], [0], [1], [1], [0], [1], [0], [0]]


[[0.4467431]
 [0.4467431]
 [0.4467431]
 [0.4467431]
 [0.4467431]
 [0.4467431]
 [0.4467431]
 [0.4467431]
 [0.4467431]
 [0.4467431]]
0.67321557
[[1], [0], [1], [0], [1], [0], [1], [0], [1], [1]]
[[0.44650862]
 [0.44650862]
 [0.44650862]
 [0.44650862]
 [0.44650862]
 [0.44650862]
 [0.44650862]
 [0.44650862]
 [0.44650862]
 [0.44650862]]
0.7178641
[[0], [0], [1], [1], [1], [1], [1], [0], [0], [0]]
[[0.44630596]
 [0.44630596]
 [0.44630596]
 [0.44630596]
 [0.44630596]
 [0.44630596]
 [0.44630596]
 [0.44630596]
 [0.44630596]
 [0.44630596]]
0.85173357
[[1], [0], [0], [0], [0], [0], [0], [0], [1], [0]]
[[0.44609633]
 [0.44609633]
 [0.44609633]
 [0.44609633]
 [0.44609633]
 [0.44609633]
 [0.44609633]
 [0.44609633]
 [0.44609633]
 [0.44609633]]
0.6732092
[[1], [1], [0], [1], [0], [1], [0], [1], [1], [0]]
[[0.44578323]
 [0.44578323]
 [0.44578323]
 [0.44578323]
 [0.44578323]
 [0.44578323]
 [0.44578323]
 [0.44578323]
 [0.44578323]
 [0.44578323]]
0.7177845
[[1], [1], [1], [1], [0], [0], [0], [1], [0], [0]

[[0.4341242]
 [0.4341242]
 [0.4341242]
 [0.4341242]
 [0.4341242]
 [0.4341242]
 [0.4341242]
 [0.4341242]
 [0.4341242]
 [0.4341242]]
0.8033473
[[1], [1], [0], [0], [1], [0], [0], [0], [0], [0]]
[[0.43391228]
 [0.43391228]
 [0.43391228]
 [0.43391228]
 [0.43391228]
 [0.43391228]
 [0.43391228]
 [0.43391228]
 [0.43391228]
 [0.43391228]]
0.75989103
[[0], [0], [1], [0], [0], [0], [0], [1], [1], [1]]
[[0.43361354]
 [0.43361354]
 [0.43361354]
 [0.43361354]
 [0.43361354]
 [0.43361354]
 [0.43361354]
 [0.43361354]
 [0.43361354]
 [0.43361354]]
0.67310655
[[1], [1], [0], [0], [0], [1], [1], [1], [1], [0]]
[[0.43316162]
 [0.43316162]
 [0.43316162]
 [0.43316162]
 [0.43316162]
 [0.43316162]
 [0.43316162]
 [0.43316162]
 [0.43316162]
 [0.43316162]]
0.75973576
[[0], [0], [1], [1], [0], [1], [0], [0], [1], [0]]
[[0.4327076]
 [0.4327076]
 [0.4327076]
 [0.4327076]
 [0.4327076]
 [0.4327076]
 [0.4327076]
 [0.4327076]
 [0.4327076]
 [0.4327076]]
0.7163713
[[0], [0], [0], [1], [1], [1], [1], [0], [1], [0]]
[[0.432

[[0.4221135]
 [0.4221135]
 [0.4221135]
 [0.4221135]
 [0.4221135]
 [0.4221135]
 [0.4221135]
 [0.4221135]
 [0.4221135]
 [0.4221135]]
0.7152563
[[1], [1], [0], [1], [1], [0], [0], [0], [1], [0]]
[[0.42178723]
 [0.42178723]
 [0.42178723]
 [0.42178723]
 [0.42178723]
 [0.42178723]
 [0.42178723]
 [0.42178723]
 [0.42178723]
 [0.42178723]]
0.6308649
[[1], [0], [1], [1], [1], [0], [0], [1], [1], [1]]
[[0.42154944]
 [0.42154944]
 [0.42154944]
 [0.42154944]
 [0.42154944]
 [0.42154944]
 [0.42154944]
 [0.42154944]
 [0.42154944]
 [0.42154944]]
0.67304265
[[1], [0], [1], [1], [0], [0], [1], [1], [0], [1]]
[[0.42139095]
 [0.42139095]
 [0.42139095]
 [0.42139095]
 [0.42139095]
 [0.42139095]
 [0.42139095]
 [0.42139095]
 [0.42139095]
 [0.42139095]]
0.7151811
[[0], [1], [1], [0], [1], [1], [0], [0], [0], [1]]
[[0.42132375]
 [0.42132375]
 [0.42132375]
 [0.42132375]
 [0.42132375]
 [0.42132375]
 [0.42132375]
 [0.42132375]
 [0.42132375]
 [0.42132375]]
0.63090944
[[1], [1], [1], [1], [1], [1], [0], [1], [0], [0]

[[0.41180235]
 [0.41180235]
 [0.41180235]
 [0.41180235]
 [0.41180235]
 [0.41180235]
 [0.41180235]
 [0.41180235]
 [0.41180235]
 [0.41180235]]
0.63183624
[[0], [1], [1], [0], [1], [0], [1], [1], [1], [1]]
[[0.41170248]
 [0.41170248]
 [0.41170248]
 [0.41170248]
 [0.41170248]
 [0.41170248]
 [0.41170248]
 [0.41170248]
 [0.41170248]
 [0.41170248]]
0.59067583
[[1], [1], [1], [0], [1], [1], [1], [1], [0], [1]]
[[0.41162297]
 [0.41162297]
 [0.41162297]
 [0.41162297]
 [0.41162297]
 [0.41162297]
 [0.41162297]
 [0.41162297]
 [0.41162297]
 [0.41162297]]
0.71417844
[[1], [1], [0], [0], [1], [1], [1], [0], [0], [0]]
[[0.4115306]
 [0.4115306]
 [0.4115306]
 [0.4115306]
 [0.4115306]
 [0.4115306]
 [0.4115306]
 [0.4115306]
 [0.4115306]
 [0.4115306]]
0.59071
[[1], [1], [1], [0], [1], [1], [1], [1], [1], [0]]
[[0.41134936]
 [0.41134936]
 [0.41134936]
 [0.41134936]
 [0.41134936]
 [0.41134936]
 [0.41134936]
 [0.41134936]
 [0.41134936]
 [0.41134936]]
0.7552856
[[1], [0], [0], [0], [1], [0], [0], [0], [1], [1]]

[[0.40126503]
 [0.40126503]
 [0.40126503]
 [0.40126503]
 [0.40126503]
 [0.40126503]
 [0.40126503]
 [0.40126503]
 [0.40126503]
 [0.40126503]]
0.75326675
[[1], [0], [0], [1], [1], [0], [1], [0], [0], [0]]
[[0.40088558]
 [0.40088558]
 [0.40088558]
 [0.40088558]
 [0.40088558]
 [0.40088558]
 [0.40088558]
 [0.40088558]
 [0.40088558]
 [0.40088558]]
0.67301416
[[0], [1], [1], [0], [0], [0], [1], [1], [1], [1]]
[[0.40053126]
 [0.40053126]
 [0.40053126]
 [0.40053126]
 [0.40053126]
 [0.40053126]
 [0.40053126]
 [0.40053126]
 [0.40053126]
 [0.40053126]]
0.71306765
[[0], [1], [1], [1], [1], [0], [0], [1], [0], [0]]
[[0.40036622]
 [0.40036622]
 [0.40036622]
 [0.40036622]
 [0.40036622]
 [0.40036622]
 [0.40036622]
 [0.40036622]
 [0.40036622]
 [0.40036622]]
0.63297814
[[1], [1], [1], [1], [1], [0], [0], [1], [0], [1]]
[[0.40008417]
 [0.40008417]
 [0.40008417]
 [0.40008417]
 [0.40008417]
 [0.40008417]
 [0.40008417]
 [0.40008417]
 [0.40008417]
 [0.40008417]]
0.6330067
[[1], [0], [1], [1], [1], [0], [0], [

[[0.3912554]
 [0.3912554]
 [0.3912554]
 [0.3912554]
 [0.3912554]
 [0.3912554]
 [0.3912554]
 [0.3912554]
 [0.3912554]
 [0.3912554]]
0.63391036
[[1], [1], [0], [1], [1], [1], [0], [1], [1], [0]]
[[0.39091626]
 [0.39091626]
 [0.39091626]
 [0.39091626]
 [0.39091626]
 [0.39091626]
 [0.39091626]
 [0.39091626]
 [0.39091626]
 [0.39091626]]
0.8294035
[[0], [1], [0], [1], [0], [0], [0], [0], [0], [0]]
[[0.39077967]
 [0.39077967]
 [0.39077967]
 [0.39077967]
 [0.39077967]
 [0.39077967]
 [0.39077967]
 [0.39077967]
 [0.39077967]
 [0.39077967]]
0.8293494
[[0], [0], [0], [0], [1], [0], [0], [1], [0], [0]]
[[0.39060515]
 [0.39060515]
 [0.39060515]
 [0.39060515]
 [0.39060515]
 [0.39060515]
 [0.39060515]
 [0.39060515]
 [0.39060515]
 [0.39060515]]
0.7511592
[[0], [1], [0], [1], [0], [1], [0], [0], [0], [1]]
[[0.3904331]
 [0.3904331]
 [0.3904331]
 [0.3904331]
 [0.3904331]
 [0.3904331]
 [0.3904331]
 [0.3904331]
 [0.3904331]
 [0.3904331]]
0.63399553
[[1], [0], [1], [1], [0], [1], [1], [1], [1], [0]]
[[0.3901

In [ ]:
validation.to_pickle('../validation_set.pkl')

- Normalizar colunas nao categoricas do dataframe
- Eliminar linhas iguais do dataframe