In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../csvteste.csv', delimiter='\t')

In [3]:
data = data.drop(['Unnamed: 0'], axis=1)

In [4]:
from sklearn.model_selection import train_test_split
data, validation = train_test_split(data, test_size=0.1)

In [5]:
data

data         label
35990  [0.007345093149582114, 0.05673758865248227, 0....  [-1, -1, -1]
17410  [0.00013885129307019846, 0.0070921985815602835...  [-1, -1, -1]
20182  [0.0010126326625927605, 0.0, 0.0, 6.7225534947...  [-1, -1, -1]
19209  [0.0006984640802925134, 0.0, 0.0, 0.0009478800...   [-1, -1, 1]
48802  [0.0011795347219397665, 0.05673758865248227, 0...  [-1, -1, -1]
23184  [0.0006886463120956307, 0.05673758865248227, 0...  [-1, -1, -1]
40474  [0.0008850016760332851, 0.05673758865248227, 0...  [-1, -1, -1]
8436   [0.0011402636491522357, 0.10638297872340426, 0...  [-1, -1, -1]
11325  [0.0009733615898052295, 0.05673758865248227, 0...  [-1, -1, -1]
22430  [0.0013366190130898901, 0.0070921985815602835,...  [-1, -1, -1]
18771  [0.0004922909481579763, 0.05673758865248227, 0...  [-1, -1, -1]
19922  [0.0009831793580021122, 0.05673758865248227, 0...   [-1, -1, 1]
3929   [0.0017293297409651989, 0.05673758865248227, 0...  [-1, -1, -1]
38712  [0.0010715392717740566, 0.0070921985815602835,...  [-1, -1, -1]
17973  [0.00024684674323590837, 0.05673758865248227, ...  [-1, -1, -1]
20874  [0.003987416426248224, 0.20567375886524822, 0....  [-1, -1, -1]
37071  [0.005253908523646095, 0.15602836879432624, 0....  [-1, -1, -1]
39228  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
9125   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
45594  [0.000502108716354859, 0.0070921985815602835, ...   [-1, 1, -1]
31834  [0.0011795347219397665, 0.05673758865248227, 0...  [-1, -1, -1]
36897  [0.0012482590993179456, 0.05673758865248227, 0...  [-1, -1, -1]
21587  [0.0011598991855460011, 0.05673758865248227, 0...  [-1, -1, -1]
26322  [0.0018765962639184395, 0.05673758865248227, 0...  [-1, -1, -1]
4106   [0.0009242727488208159, 0.05673758865248227, 0...  [-1, -1, -1]
37903  [0.004134682949201465, 0.05673758865248227, 0....  [-1, -1, -1]
43299  [0.0004922909481579763, 0.05673758865248227, 0...  [-1, -1, -1]
41082  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
7991   [0.0017489652773589642, 0.20567375886524822, 0...   [-1, 1, -1]
49648  [0.0018471429593277914, 0.05673758865248227, 0...  [-1, -1, -1]
...                                                  ...           ...
12046  [0.00029593558422032196, 0.0070921985815602835...  [-1, -1, -1]
33269  [0.0013562545494836555, 0.05673758865248227, 0...  [-1, -1, -1]
48419  [0.0012580768675148283, 0.05673758865248227, 0...  [-1, -1, -1]
14994  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
31535  [0.0018176896547371433, 0.05673758865248227, 0...  [-1, -1, -1]
36076  [0.0008850016760332851, 0.05673758865248227, 0...  [-1, -1, -1]
10246  [0.0006886463120956307, 0.0070921985815602835,...  [-1, -1, -1]
6270   [0.0015231566088306618, 0.0070921985815602835,...  [-1, -1, -1]
16362  [0.0018765962639184395, 0.10638297872340426, 0...  [-1, -1, -1]
20205  [1.4025383138403883e-06, 0.0070921985815602835...  [-1, -1, -1]
31950  [0.001307165708499242, 0.05673758865248227, 0....   [-1, 1, -1]
44369  [0.002377302441959458, 0.10638297872340426, 0....  [-1, -1, -1]
12384  [0.0003744777297953837, 0.0070921985815602835,...  [-1, -1, -1]
34791  [3.0855842904488546e-05, 0.05673758865248227, ...  [-1, -1, -1]
43962  [0.0002861178160234392, 0.0070921985815602835,...  [-1, -1, -1]
15411  [0.00045301987537044544, 0.0070921985815602835...  [-1, -1, -1]
27588  [0.004026687499035755, 0.05673758865248227, 4....  [-1, -1, -1]
11628  [0.0004726554117642109, 0.0070921985815602835,...  [-1, -1, -1]
28196  [0.005037917623314675, 0.05673758865248227, 0....  [-1, -1, -1]
23389  [0.0032805371160726684, 0.05673758865248227, 0...  [-1, -1, -1]
23470  [0.00044320210717356274, 0.05673758865248227, ...  [-1, -1, -1]
38906  [0.0009929971261989949, 0.10638297872340426, 0...   [-1, 1, -1]
33014  [0.004164136253792113, 0.05673758865248227, 0....  [-1, -1, -1]
1389   [0.00020757567044837747, 0.0070921985815602835...   [-1, -1, 1]
8759   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
4527 

In [6]:
validation

data         label
14532  [0.0012089880265304148, 0.05673758865248227, 4...  [-1, -1, -1]
38739  [0.0010813570399709393, 0.10638297872340426, 0...  [-1, -1, -1]
46355  [0.002662017719669057, 0.05673758865248227, 0....  [-1, -1, -1]
47600  [0.003957963121657576, 0.10638297872340426, 0....  [-1, -1, -1]
3942   [0.002259489223596866, 0.10638297872340426, 0....  [-1, -1, -1]
9581   [0.0013366190130898901, 0.05673758865248227, 0...  [-1, -1, -1]
5124   [0.0010519037353802912, 0.05673758865248227, 0...  [-1, -1, -1]
19423  [0.0006984640802925134, 0.0070921985815602835,...  [-1, -1, -1]
10498  [0.0002763000478265565, 0.0070921985815602835,...  [-1, -1, -1]
11631  [0.0012286235629241802, 0.05673758865248227, 0...  [-1, -1, -1]
15368  [0.0022398536872031, 0.10638297872340426, 0.01...  [-1, -1, -1]
44187  [0.0025049334285189334, 0.05673758865248227, 0...   [-1, -1, 1]
41355  [0.001267894635711711, 0.0, 0.0, 0.00108233111...   [-1, 1, -1]
18625  [0.0018373251911309087, 0.05673758865248227, 0...  [-1, -1, -1]
33638  [0.0016115165226026063, 0.10638297872340426, 0...   [-1, -1, 1]
9207   [0.001091174808167822, 0.05673758865248227, 0....  [-1, -1, -1]
36216  [0.0001683045976608466, 0.0070921985815602835,...  [-1, -1, -1]
46703  [0.00035484219340161825, 0.0070921985815602835...  [-1, -1, -1]
8906   [0.00018794013405461205, 0.0070921985815602835...  [-1, -1, -1]
21071  [0.0015329743770275445, 0.05673758865248227, 0...  [-1, -1, -1]
40053  [0.00931846455715554, 0.05673758865248227, 0.0...  [-1, -1, -1]
45137  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
44242  [0.0023674846737625757, 0.10638297872340426, 0...  [-1, -1, -1]
46119  [0.0011598991855460011, 0.05673758865248227, 0...  [-1, -1, -1]
2770   [0.000747552921276927, 0.0070921985815602835, ...  [-1, -1, -1]
1145   [0.011193658282760139, 0.05673758865248227, 0....  [-1, -1, -1]
26574  [3.0855842904488546e-05, 0.0070921985815602835...  [-1, -1, -1]
34066  [0.0006101041665205689, 0.05673758865248227, 0...  [-1, -1, -1]
38342  [0.001061721503577174, 0.05673758865248227, 0....  [-1, -1, -1]
35483  [0.015464387448404122, 0.10638297872340426, 0....   [-1, -1, 1]
...                                                  ...           ...
27127  [0.0014838855360431308, 0.05673758865248227, 0...  [-1, -1, -1]
25228  [0.0006591930075049825, 0.0070921985815602835,...  [-1, -1, -1]
12175  [0.006432040707272021, 0.05673758865248227, 0....  [-1, -1, -1]
41042  [2.1038074707605825e-05, 0.0070921985815602835...  [-1, -1, -1]
22119  [0.0008948194442301678, 0.05673758865248227, 0...  [-1, -1, -1]
14612  [0.0025834755740939954, 0.10638297872340426, 0...  [-1, -1, -1]
19627  [0.0052833618282367425, 0.05673758865248227, 0...  [-1, -1, -1]
19410  [0.0011893524901366492, 0.05673758865248227, 0...  [-1, -1, -1]
39888  [0.0013366190130898901, 0.0070921985815602835,...  [-1, -1, -1]
1104   [0.0011697169537428838, 0.05673758865248227, 0...   [-1, 1, -1]
5825   [0.003879420976082514, 0.05673758865248227, 0....   [-1, -1, 1]
43691  [0.001130445880955353, 0.05673758865248227, 0....  [-1, -1, -1]
21056  [7.994468388890214e-05, 0.0070921985815602835,...   [-1, -1, 1]
23852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
12001  [0.0015624276816181926, 0.0070921985815602835,...  [-1, -1, -1]
23644  [0.00202386278687168, 0.05673758865248227, 0.0...  [-1, -1, -1]
42094  [1.4025383138403883e-06, 0.0070921985815602835...  [-1, -1, -1]
24739  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
48585  [0.0031725416659069586, 0.10638297872340426, 0...  [-1, -1, -1]
40555  [0.0006984640802925134, 0.05673758865248227, 0...  [-1, -1, -1]
24306  [0.001130445880955353, 0.15602836879432624, 0....  [-1, -1, -1]
13412  [0.001297347940302359, 0.05673758865248227, 8....   [-1, 1, -1]
41055  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
14562  [0.0024362090511407543, 0.05673758865248227, 0...  [-1, -1, -1]
4706   [0.0007082818484893961, 0.05673758865248227, 0...  [-1, -1, -1]
7566 

In [7]:
from ast import literal_eval

In [8]:
data

data         label
35990  [0.007345093149582114, 0.05673758865248227, 0....  [-1, -1, -1]
17410  [0.00013885129307019846, 0.0070921985815602835...  [-1, -1, -1]
20182  [0.0010126326625927605, 0.0, 0.0, 6.7225534947...  [-1, -1, -1]
19209  [0.0006984640802925134, 0.0, 0.0, 0.0009478800...   [-1, -1, 1]
48802  [0.0011795347219397665, 0.05673758865248227, 0...  [-1, -1, -1]
23184  [0.0006886463120956307, 0.05673758865248227, 0...  [-1, -1, -1]
40474  [0.0008850016760332851, 0.05673758865248227, 0...  [-1, -1, -1]
8436   [0.0011402636491522357, 0.10638297872340426, 0...  [-1, -1, -1]
11325  [0.0009733615898052295, 0.05673758865248227, 0...  [-1, -1, -1]
22430  [0.0013366190130898901, 0.0070921985815602835,...  [-1, -1, -1]
18771  [0.0004922909481579763, 0.05673758865248227, 0...  [-1, -1, -1]
19922  [0.0009831793580021122, 0.05673758865248227, 0...   [-1, -1, 1]
3929   [0.0017293297409651989, 0.05673758865248227, 0...  [-1, -1, -1]
38712  [0.0010715392717740566, 0.0070921985815602835,...  [-1, -1, -1]
17973  [0.00024684674323590837, 0.05673758865248227, ...  [-1, -1, -1]
20874  [0.003987416426248224, 0.20567375886524822, 0....  [-1, -1, -1]
37071  [0.005253908523646095, 0.15602836879432624, 0....  [-1, -1, -1]
39228  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
9125   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
45594  [0.000502108716354859, 0.0070921985815602835, ...   [-1, 1, -1]
31834  [0.0011795347219397665, 0.05673758865248227, 0...  [-1, -1, -1]
36897  [0.0012482590993179456, 0.05673758865248227, 0...  [-1, -1, -1]
21587  [0.0011598991855460011, 0.05673758865248227, 0...  [-1, -1, -1]
26322  [0.0018765962639184395, 0.05673758865248227, 0...  [-1, -1, -1]
4106   [0.0009242727488208159, 0.05673758865248227, 0...  [-1, -1, -1]
37903  [0.004134682949201465, 0.05673758865248227, 0....  [-1, -1, -1]
43299  [0.0004922909481579763, 0.05673758865248227, 0...  [-1, -1, -1]
41082  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
7991   [0.0017489652773589642, 0.20567375886524822, 0...   [-1, 1, -1]
49648  [0.0018471429593277914, 0.05673758865248227, 0...  [-1, -1, -1]
...                                                  ...           ...
12046  [0.00029593558422032196, 0.0070921985815602835...  [-1, -1, -1]
33269  [0.0013562545494836555, 0.05673758865248227, 0...  [-1, -1, -1]
48419  [0.0012580768675148283, 0.05673758865248227, 0...  [-1, -1, -1]
14994  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
31535  [0.0018176896547371433, 0.05673758865248227, 0...  [-1, -1, -1]
36076  [0.0008850016760332851, 0.05673758865248227, 0...  [-1, -1, -1]
10246  [0.0006886463120956307, 0.0070921985815602835,...  [-1, -1, -1]
6270   [0.0015231566088306618, 0.0070921985815602835,...  [-1, -1, -1]
16362  [0.0018765962639184395, 0.10638297872340426, 0...  [-1, -1, -1]
20205  [1.4025383138403883e-06, 0.0070921985815602835...  [-1, -1, -1]
31950  [0.001307165708499242, 0.05673758865248227, 0....   [-1, 1, -1]
44369  [0.002377302441959458, 0.10638297872340426, 0....  [-1, -1, -1]
12384  [0.0003744777297953837, 0.0070921985815602835,...  [-1, -1, -1]
34791  [3.0855842904488546e-05, 0.05673758865248227, ...  [-1, -1, -1]
43962  [0.0002861178160234392, 0.0070921985815602835,...  [-1, -1, -1]
15411  [0.00045301987537044544, 0.0070921985815602835...  [-1, -1, -1]
27588  [0.004026687499035755, 0.05673758865248227, 4....  [-1, -1, -1]
11628  [0.0004726554117642109, 0.0070921985815602835,...  [-1, -1, -1]
28196  [0.005037917623314675, 0.05673758865248227, 0....  [-1, -1, -1]
23389  [0.0032805371160726684, 0.05673758865248227, 0...  [-1, -1, -1]
23470  [0.00044320210717356274, 0.05673758865248227, ...  [-1, -1, -1]
38906  [0.0009929971261989949, 0.10638297872340426, 0...   [-1, 1, -1]
33014  [0.004164136253792113, 0.05673758865248227, 0....  [-1, -1, -1]
1389   [0.00020757567044837747, 0.0070921985815602835...   [-1, -1, 1]
8759   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
4527 

In [9]:
data = data.reset_index()
validation = validation.reset_index()
data

index                                               data         label
0      35990  [0.007345093149582114, 0.05673758865248227, 0....  [-1, -1, -1]
1      17410  [0.00013885129307019846, 0.0070921985815602835...  [-1, -1, -1]
2      20182  [0.0010126326625927605, 0.0, 0.0, 6.7225534947...  [-1, -1, -1]
3      19209  [0.0006984640802925134, 0.0, 0.0, 0.0009478800...   [-1, -1, 1]
4      48802  [0.0011795347219397665, 0.05673758865248227, 0...  [-1, -1, -1]
5      23184  [0.0006886463120956307, 0.05673758865248227, 0...  [-1, -1, -1]
6      40474  [0.0008850016760332851, 0.05673758865248227, 0...  [-1, -1, -1]
7       8436  [0.0011402636491522357, 0.10638297872340426, 0...  [-1, -1, -1]
8      11325  [0.0009733615898052295, 0.05673758865248227, 0...  [-1, -1, -1]
9      22430  [0.0013366190130898901, 0.0070921985815602835,...  [-1, -1, -1]
10     18771  [0.0004922909481579763, 0.05673758865248227, 0...  [-1, -1, -1]
11     19922  [0.0009831793580021122, 0.05673758865248227, 0...   [-1, -1, 1]
12      3929  [0.0017293297409651989, 0.05673758865248227, 0...  [-1, -1, -1]
13     38712  [0.0010715392717740566, 0.0070921985815602835,...  [-1, -1, -1]
14     17973  [0.00024684674323590837, 0.05673758865248227, ...  [-1, -1, -1]
15     20874  [0.003987416426248224, 0.20567375886524822, 0....  [-1, -1, -1]
16     37071  [0.005253908523646095, 0.15602836879432624, 0....  [-1, -1, -1]
17     39228  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
18      9125  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
19     45594  [0.000502108716354859, 0.0070921985815602835, ...   [-1, 1, -1]
20     31834  [0.0011795347219397665, 0.05673758865248227, 0...  [-1, -1, -1]
21     36897  [0.0012482590993179456, 0.05673758865248227, 0...  [-1, -1, -1]
22     21587  [0.0011598991855460011, 0.05673758865248227, 0...  [-1, -1, -1]
23     26322  [0.0018765962639184395, 0.05673758865248227, 0...  [-1, -1, -1]
24      4106  [0.0009242727488208159, 0.05673758865248227, 0...  [-1, -1, -1]
25     37903  [0.004134682949201465, 0.05673758865248227, 0....  [-1, -1, -1]
26     43299  [0.0004922909481579763, 0.05673758865248227, 0...  [-1, -1, -1]
27     41082  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
28      7991  [0.0017489652773589642, 0.20567375886524822, 0...   [-1, 1, -1]
29     49648  [0.0018471429593277914, 0.05673758865248227, 0...  [-1, -1, -1]
...      ...                                                ...           ...
44970  12046  [0.00029593558422032196, 0.0070921985815602835...  [-1, -1, -1]
44971  33269  [0.0013562545494836555, 0.05673758865248227, 0...  [-1, -1, -1]
44972  48419  [0.0012580768675148283, 0.05673758865248227, 0...  [-1, -1, -1]
44973  14994  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01260755...  [-1, -1, -1]
44974  31535  [0.0018176896547371433, 0.05673758865248227, 0...  [-1, -1, -1]
44975  36076  [0.0008850016760332851, 0.05673758865248227, 0...  [-1, -1, -1]
44976  10246  [0.0006886463120956307, 0.0070921985815602835,...  [-1, -1, -1]
44977   6270  [0.0015231566088306618, 0.0070921985815602835,...  [-1, -1, -1]
44978  16362  [0.0018765962639184395, 0.10638297872340426, 0...  [-1, -1, -1]
44979  20205  [1.4025383138403883e-06, 0.0070921985815602835...  [-1, -1, -1]
44980  31950  [0.001307165708499242, 0.05673758865248227, 0....   [-1, 1, -1]
44981  44369  [0.002377302441959458, 0.10638297872340426, 0....  [-1, -1, -1]
44982  12384  [0.0003744777297953837, 0.0070921985815602835,...  [-1, -1, -1]
44983  34791  [3.0855842904488546e-05, 0.05673758865248227, ...  [-1, -1, -1]
44984  43962  [0.0002861178160234392, 0.0070921985815602835,...  [-1, -1, -1]
44985  15411  [0.00045301987537044544, 0.0070921985815602835...  [-1, -1, -1]
44986  27588  [0.004026687499035755, 0.05673758865248227, 4....  [-1, -1, -1]
44987  11628  [0.0004726554117642109, 0.0070921985815602835,...  [-1, -1, -1]
44988  28196  [0.005037917623314675, 0.05673758865248227, 0....  [-1, -1, -1]
44989  23389  [0.003280537116

Como o numero de valores -1 é muito superior, na hora de gerar o batch o modelo vai tender a gerar outputs negativos, por conta disso, farei uma condição para equalizar o carregamento de batches com valores -1 iguais ao de 1. Vai deixar mais lento na hora do treino, mas deve funcionar. 

In [10]:
import random
def loadbatch(dataframe, batch_size, objective):
    if objective == 'a':
        aux = 0
    elif objective == 'u':
        aux = 1
    elif objective == 'c':
        aux = 2
    else:
        print('objetivo inexistente')
    batch_x = []
    batch_y = []
    for i in range(int(batch_size)):
        randval = random.randrange(len(dataframe))
        if random.random() > 0.5:
            while literal_eval(dataframe['label'][randval])[aux]<0:
                randval = random.randrange(len(dataframe))
        else:
            while literal_eval(dataframe['label'][randval])[aux]>0:
                randval = random.randrange(len(dataframe))
        batch_x.append(literal_eval(dataframe['data'][randval]))
        if literal_eval(dataframe['label'][randval])[aux] < 0:
            batch_y.append([0])
        else:
            batch_y.append([literal_eval(dataframe['label'][randval])[aux]])
    return batch_x, batch_y

In [11]:
xdemo, ydemo = loadbatch(data, 20, 'a')
ydemo

[[0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0]]

In [12]:
singleTest = validation['label'][4449]
print(singleTest)

[-1, -1, -1]


In [13]:
import tensorflow as tf
from tensorflow.contrib import slim

In [14]:
x = tf.placeholder(tf.float32, shape=[None, 7890], name='input_placeholder')
y_ = tf.placeholder(tf.float32, shape=[None, 1])
learning_rate = tf.placeholder('float', [])

In [37]:
def model(hl):
#     hl = slim.fully_connected(tf.layers.batch_normalization(hl), 8100)
#     hl = slim.fully_connected(hl, 2000)
#     print(hl.shape)
#     hl = slim.fully_connected(hl, 2000)
#     print(hl.shape)
#     hl = tf.reshape(hl, [-1, 90, 90, 1])
#     print(hl.shape)
#     hl = tf.layers.batch_normalization(slim.conv2d(hl, 16, [7, 7]))
#     print(hl.shape)
#     hl = slim.max_pool2d(hl, [3,3], stride=2)
#     residual = hl
#     print(hl.shape)
#     hl = tf.layers.batch_normalization(slim.conv2d(hl, 32, [5, 5]))
#     print(hl.shape)
#     hl = slim.max_pool2d(hl, [3,3], stride=2)
#     print(hl.shape)
#     hl = tf.layers.batch_normalization(slim.conv2d(hl, 32, [3, 3]))
#     print(hl.shape)
#     hl = slim.max_pool2d(hl, [3,3], stride=2)
#     print(hl.shape)
#     hl = slim.flatten(hl)
#     print(hl.shape)
#     hl = tf.layers.batch_normalization(slim.fully_connected(hl, 1000))
#     print(hl.shape)
    hl = tf.layers.batch_normalization(slim.fully_connected(hl, 100))
    print(hl.shape)
    hl = tf.layers.batch_normalization(slim.fully_connected(hl, 1))
    print(hl.shape)
    return(tf.sigmoid(hl))

In [38]:
model_1 = (model(x))

(?, 100)
(?, 1)


In [39]:
# loss = tf.reduce_mean((y_ - model_1)**2)
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y_, logits=model_1))
train = tf.train.AdamOptimizer(learning_rate).minimize(loss)

In [40]:
init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [43]:
batch_size = 40
steps = 5000
rate = 0.0001

In [ ]:
with tf.Session() as sess:
    sess.run(init)
    for i in range(steps):
        batch_x, batch_y = loadbatch(data, batch_size, objective='a')
        feed = {x:batch_x, y_:batch_y, learning_rate:rate}
        sess.run(train, feed_dict=feed)
        
        if i%10 == 0:
            val_x, val_y = loadbatch(validation, 10, objective='a')
            feed_validation = {x:val_x, y_:val_y}
            print(sess.run(model_1, feed_dict=feed_validation))
            print(sess.run(loss, feed_dict=feed_validation))
            print(val_y)
            if i>1000:
                rate = 3e-4
            
    location = './saved_models/kdd_model_3.ckpt'
    save_path = (saver.save(sess, location))
    print('model saved in', location)

[[0.5293838 ]
 [0.500025  ]
 [0.51944715]
 [0.52944326]
 [0.5017486 ]
 [0.500025  ]
 [0.51971525]
 [0.500025  ]
 [0.50181067]
 [0.51623887]]
0.8265276
[[0], [0], [0], [1], [0], [1], [1], [0], [0], [0]]
[[0.5069276 ]
 [0.49985543]
 [0.49985543]
 [0.5166223 ]
 [0.49985543]
 [0.49985543]
 [0.49985543]
 [0.51660407]
 [0.49985543]
 [0.49985543]]
0.7242089
[[1], [1], [0], [1], [0], [0], [1], [0], [1], [0]]
[[0.5070849 ]
 [0.49964035]
 [0.50640583]
 [0.49964035]
 [0.510779  ]
 [0.49964035]
 [0.49964035]
 [0.49964035]
 [0.49964038]
 [0.49964038]]
0.82486475
[[0], [1], [1], [0], [0], [0], [1], [0], [0], [0]]
[[0.49939638]
 [0.49939638]
 [0.4996998 ]
 [0.5356528 ]
 [0.5195546 ]
 [0.49939638]
 [0.49939638]
 [0.49939638]
 [0.51233596]
 [0.50686157]]
0.7211434
[[0], [0], [0], [1], [1], [1], [0], [0], [1], [1]]
[[0.49917617]
 [0.49917617]
 [0.49917617]
 [0.49917617]
 [0.49917617]
 [0.49917617]
 [0.5182725 ]
 [0.49917617]
 [0.4999882 ]
 [0.53828   ]]
0.67185163
[[1], [0], [0], [1], [0], [0], [1], [1]

[[0.65298694]
 [0.6048939 ]
 [0.5086889 ]
 [0.49092278]
 [0.49092278]
 [0.6828544 ]
 [0.52571714]
 [0.49092278]
 [0.6828544 ]
 [0.4909228 ]]
0.60084444
[[1], [1], [0], [0], [0], [1], [1], [1], [1], [1]]
[[0.49066162]
 [0.49066162]
 [0.49066162]
 [0.5127539 ]
 [0.49066162]
 [0.49066162]
 [0.49066162]
 [0.49066162]
 [0.5062562 ]
 [0.50614876]]
0.97158414
[[0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]
[[0.5940039 ]
 [0.49043655]
 [0.6948614 ]
 [0.49043655]
 [0.49043655]
 [0.54003704]
 [0.49043655]
 [0.504608  ]
 [0.49043658]
 [0.6924244 ]]
0.8358409
[[0], [0], [1], [0], [0], [0], [1], [1], [0], [0]]
[[0.5617733 ]
 [0.6620457 ]
 [0.49021024]
 [0.49021024]
 [0.61444247]
 [0.49021024]
 [0.49021024]
 [0.5300108 ]
 [0.5603727 ]
 [0.51393116]]
0.7753452
[[1], [1], [1], [0], [0], [0], [0], [1], [0], [0]]
[[0.5675708 ]
 [0.48997197]
 [0.50390995]
 [0.64072245]
 [0.6047842 ]
 [0.54016167]
 [0.7740288 ]
 [0.48997197]
 [0.69813985]
 [0.631216  ]]
0.64291793
[[1], [0], [0], [1], [1], [0], [1], [0

[[0.71139646]
 [0.6201543 ]
 [0.6666552 ]
 [0.4804757 ]
 [0.8298667 ]
 [0.5725483 ]
 [0.4804757 ]
 [0.7544841 ]
 [0.4804757 ]
 [0.61419046]]
0.63774014
[[1], [0], [1], [0], [1], [1], [0], [1], [0], [1]]
[[0.87449825]
 [0.7732714 ]
 [0.4801877 ]
 [0.53564763]
 [0.4801877 ]
 [0.4801877 ]
 [0.4801877 ]
 [0.4801877 ]
 [0.48018768]
 [0.800174  ]]
0.890406
[[1], [0], [0], [1], [0], [0], [0], [0], [0], [0]]
[[0.47993225]
 [0.56316996]
 [0.47993225]
 [0.47993225]
 [0.6509632 ]
 [0.62629426]
 [0.5540598 ]
 [0.5022314 ]
 [0.47993225]
 [0.52584845]]
0.71223104
[[1], [0], [0], [0], [1], [1], [1], [0], [0], [1]]
[[0.47966656]
 [0.5424526 ]
 [0.47966656]
 [0.6474371 ]
 [0.6959319 ]
 [0.47966656]
 [0.47966656]
 [0.47966656]
 [0.47966653]
 [0.47966653]]
0.7534349
[[0], [1], [0], [1], [1], [0], [0], [1], [0], [0]]
[[0.5767194 ]
 [0.6460786 ]
 [0.6503569 ]
 [0.5633193 ]
 [0.47942114]
 [0.5501956 ]
 [0.47942114]
 [0.85116774]
 [0.6242365 ]
 [0.5060845 ]]
0.6067108
[[1], [1], [1], [1], [1], [0], [0], [1],

In [ ]:
validation.to_pickle('../validation_set.pkl')